const SB_URL='https://ayfdkemjykhxqirlzbzw.supabase.co';
const SB_KEY='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(SB_URL,SB_KEY):null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentPage='inicio',currentAgent='MilMo Guide',catalog=[];
const agentInfo={
'MilMo Guide':['Guia do MilMo','🤖'], 'Rebirth Assistant':['Assistente Rebirth','⚡'], 'Medal Hunter':['Caçador de Medalhas','🏅'], 'Island Explorer':['Explorador de Ilhas','🗺️'], 'Mission Agent':['Agente de Missões','🧭'], 'Devourer Hunter':['Caçador de Devoradores','🦷'], 'Invader Hunter':['Caçador de Invasores','👾'], 'Weapon Master':['Mestre das Armas','⚔️'], 'Ranking Analyst':['Analista de Rankings','📊'], 'Legacy Archivist':['Arquivista Histórico','📜'], 'Community Guide':['Guia da Comunidade','💬'], 'Moderation Assistant':['Assistente de Moderação','🛡️']};
const pageAgents={inicio:'MilMo Guide',rebirth:'Rebirth Assistant',conquistas:'Medal Hunter',pedia:'Island Explorer',progresso:'MilMo Guide',rankings:'Ranking Analyst',hall:'Legacy Archivist',comunidade:'Community Guide',admin:'Moderation Assistant'};
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function go(id){if(!$('#'+id))return;currentPage=id;$$('.page').forEach(x=>x.classList.toggle('on',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.go===id));history.replaceState(null,'','#'+id);$('#nav').classList.remove('open');setAgent(pageAgents[id]||'MilMo Guide');track(id);scrollTo({top:0,behavior:'smooth'});if(id==='admin')loadTraffic()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');if(location.hash&&$(location.hash))go(location.hash.slice(1));
function uid(storage,key){let x=storage.getItem(key);if(!x){x=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();storage.setItem(key,x)}return x}
const visitor=uid(localStorage,'mlh_visitor_id'),session=uid(sessionStorage,'mlh_session_id');
function device(){return innerWidth<768?'Celular':innerWidth<1100?'Tablet':'Desktop'}function source(){if(!document.referrer)return'Direto';try{const h=new URL(document.referrer).hostname;if(h.includes('google'))return'Google';if(h.includes('facebook'))return'Facebook';if(h.includes('discord'))return'Discord';if(h.includes('youtube'))return'YouTube';return h}catch{return'Direto'}}
async function track(page){if(!db||location.protocol==='file:')return;try{await db.from('traffic_events').insert({visitor_id:visitor,session_id:session,event_type:'route_view',page,path:location.pathname+location.hash,source:source(),device_type:device(),language:navigator.language,screen_width:screen.width,screen_height:screen.height})}catch(e){console.warn(e)}}
async function loadCatalog(){if(!db)return;const {data,error}=await db.from('achievement_catalog').select('slug,title,category,era,description,target_value,unit,points,rarity,source_url').order('category').order('target_value');if(error){$('#achievementGrid').innerHTML='<div class="card"><p class="error">Não foi possível carregar o catálogo.</p></div>';return}catalog=data||[];$('#statCatalog').textContent=catalog.length;renderCatalog(catalog);$('#subAchievement').innerHTML='<option value="">Outra / não listada</option>'+catalog.map(a=>`<option value="${esc(a.slug)}">${esc(a.title)} — ${esc(a.category)}</option>`).join('')}
function renderCatalog(items){$('#achievementGrid').innerHTML=items.map(a=>`<article class="card"><span class="tag ${a.era==='Legacy'?'gold':'green'}">${esc(a.era)}</span><h3>${esc(a.title)}</h3><p class="muted">${esc(a.description||'')}</p>${a.target_value?`<p><b>${Number(a.target_value).toLocaleString('pt-BR')}</b> ${esc(a.unit||'')}</p>`:''}<p><span class="tag">${esc(a.category)}</span> <span class="tag purple">${esc(a.rarity||'')}</span></p>${a.source_url?`<a class="link" href="${esc(a.source_url)}" target="_blank" rel="noopener">Ver fonte ↗</a>`:''}</article>`).join('')||'<div class="card"><p class="muted">Nenhum resultado.</p></div>'}
$('#achievementSearchBtn').onclick=()=>{const q=$('#achievementSearch').value.toLowerCase().trim();renderCatalog(catalog.filter(a=>[a.title,a.category,a.era,a.description].join(' ').toLowerCase().includes(q)))};$('#achievementSearch').addEventListener('input',e=>{if(!e.target.value)renderCatalog(catalog)});
async function loadAreas(){if(!db)return;const {data}=await db.from('milmo_areas').select('slug,name,adventure,description,source_url').order('name');const rows=data||[];$('#areaGrid').innerHTML=rows.map(a=>{const saved=JSON.parse(localStorage.getItem('tokens_'+a.slug)||'[]');return`<div class="area-card"><span class="tag">${esc(a.adventure||'Legacy')}</span><h3>${esc(a.name)}</h3><p>${esc(a.description||'')}</p><div class="token-checks">${Array.from({length:8},(_,i)=>`<button class="${saved.includes(i+1)?'done':''}" data-token-area="${esc(a.slug)}" data-token="${i+1}">${i+1}</button>`).join('')}</div><small class="muted">Checklist local • ${saved.length}/8</small><p style="margin-top:9px"><a class="link" href="${esc(a.source_url||'#')}" target="_blank">Fonte/guia ↗</a></p></div>`}).join('')||'<div class="area-card">Nenhuma área catalogada.</div>';$$('[data-token-area]').forEach(b=>b.onclick=()=>toggleToken(b.dataset.tokenArea,Number(b.dataset.token)))}
function toggleToken(area,n){let arr=JSON.parse(localStorage.getItem('tokens_'+area)||'[]');arr=arr.includes(n)?arr.filter(x=>x!==n):[...arr,n].sort((a,b)=>a-b);localStorage.setItem('tokens_'+area,JSON.stringify(arr));loadAreas()}
async function loadKnowledge(){if(!db)return;const {data}=await db.from('knowledge_entries').select('section,title,content,source_url,source_type').eq('status','approved').order('section');$('#knowledgeList').innerHTML=(data||[]).map(k=>`<div class="list-item"><strong>${esc(k.title)}</strong><small>${esc(k.section)} • ${esc(k.source_type||'fonte')}</small><p>${esc(k.content)}</p>${k.source_url?`<a class="link" href="${esc(k.source_url)}" target="_blank">Fonte ↗</a>`:''}</div>`).join('')}
const thresholds={dev:[50,125,250,500,750,1500,3000,5000],inv:[5,10,25,50,150,300,600,1000],weapon:[150,300,600,1800,5000,10000,25000,50000]};
function setupProgress(inputId,barId,statusId,milesId,key,labels){const input=$(inputId),bar=$(barId),status=$(statusId),miles=$(milesId),ts=thresholds[key];input.value=localStorage.getItem('progress_'+key)||'';function render(){const v=Math.max(0,Number(input.value||0));localStorage.setItem('progress_'+key,v);const max=ts.at(-1),pct=Math.min(100,v/max*100);bar.style.width=pct+'%';const next=ts.find(x=>x>v);status.textContent=v>=max?labels.done:`${v.toLocaleString('pt-BR')} concluídos • próximo marco: ${(next||max).toLocaleString('pt-BR')}`;miles.innerHTML=ts.map(x=>`<span class="${v>=x?'done':''}">${x.toLocaleString('pt-BR')}</span>`).join('')}input.addEventListener('input',render);render()}
setupProgress('#devCount','#devBar','#devStatus','#devMilestones','dev',{done:'5.000 concluídos — World Saver alcançado.'});setupProgress('#invCount','#invBar','#invStatus','#invMilestones','inv',{done:'1.000 concluídos — The Last Line of Defense alcançado.'});setupProgress('#weaponCount','#weaponBar','#weaponStatus','#weaponMilestones','weapon',{done:'50.000 batalhas — progressão máxima desta arma.'});
['goal1','goal2','goal3'].forEach(id=>$('#'+id).value=localStorage.getItem('mlh_'+id)||'');$('#saveGoals').onclick=()=>{['goal1','goal2','goal3'].forEach(id=>localStorage.setItem('mlh_'+id,$('#'+id).value));$('#goalMsg').className='message ok';$('#goalMsg').textContent='Objetivos salvos neste navegador.'};
async function loadRankings(){if(!db)return;const {data}=await db.from('achievement_submissions').select('player_name,character_name,server,era,title,confidence,created_at').eq('status','approved').order('created_at',{ascending:true});const rows=data||[];const score={};rows.forEach(r=>{const k=r.character_name||r.player_name;score[k]=score[k]||{name:k,server:r.server||r.era||'—',count:0,points:0};score[k].count++;score[k].points+=r.confidence==='A'?400:r.confidence==='B'?250:r.confidence==='C'?150:100});const list=Object.values(score).sort((a,b)=>b.points-a.points);$('#rankingList').innerHTML=list.length?list.map((r,i)=>`<div class="rank-row"><span class="rank-num">#${i+1}</span><span><b>${esc(r.name)}</b><small class="muted" style="display:block">${r.count} registro(s) aprovado(s)</small></span><span>${esc(r.server)}</span><span><b>${r.points}</b> pts</span></div>`).join(''):'<p class="muted">Ainda não há conquistas comunitárias aprovadas suficientes para formar um ranking real.</p>'}
const bad=['fdp','filhodaputa','filhadaputa','idiota','imbecil','arrombado','desgracado'];function offensive(t){return bad.some(w=>t.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'').includes(w))}
$('#commentForm').onsubmit=async e=>{e.preventDefault();const name=$('#commentPlayer').value.trim(),body=$('#commentBody').value.trim(),m=$('#commentMsg');if(offensive(body)){m.className='message error';m.textContent='Comentário bloqueado por linguagem ofensiva.';return}if(!db){m.className='message error';m.textContent='Supabase indisponível.';return}const {error}=await db.from('community_comments').insert({player_name:name,body,status:'pending'});m.className='message '+(error?'error':'ok');m.textContent=error?'Não foi possível enviar agora.':'Comentário recebido e enviado para moderação.';if(!error)e.target.reset()};
function openSubmission(){$('#submissionModal').classList.add('on')}$('#openSubmission').onclick=openSubmission;$('#openSubmission2').onclick=openSubmission;$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('on'));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('on')});
$('#subAchievement').onchange=e=>{const a=catalog.find(x=>x.slug===e.target.value);if(a)$('#subTitle').value=a.title};$('#submissionForm').onsubmit=async e=>{e.preventDefault();const m=$('#subMsg'),desc=$('#subDesc').value.trim();if(offensive(desc)){m.className='message error';m.textContent='Texto bloqueado por linguagem ofensiva.';return}if(!db){m.className='message error';m.textContent='Supabase indisponível.';return}const payload={player_name:$('#subPlayer').value.trim(),character_name:$('#subPlayer').value.trim(),server:$('#subServer').value,era:$('#subEra').value,achievement_slug:$('#subAchievement').value||null,title:$('#subTitle').value.trim(),description:desc,evidence_url:$('#subEvidence').value.trim()||null,status:'pending',confidence:'D'};const {error}=await db.from('achievement_submissions').insert(payload);m.className='message '+(error?'error':'ok');m.textContent=error?'Erro ao enviar: '+error.message:'Conquista enviada. Ela ficará pendente até revisão.';if(!error)e.target.reset()};
async function loadTraffic(){if(!db)return;try{const {data,error}=await db.from('traffic_totals').select('views,visitors,sessions,updated_at').eq('id',1).maybeSingle();if(error)throw error;const d=data||{};$('#trafficViews').textContent=Number(d.views||0).toLocaleString('pt-BR');$('#trafficVisitors').textContent=Number(d.visitors||0).toLocaleString('pt-BR');$('#trafficSessions').textContent=Number(d.sessions||0).toLocaleString('pt-BR');$('#statViews').textContent=Number(d.views||0).toLocaleString('pt-BR');$('#trafficMsg').className='message ok';$('#trafficMsg').textContent='Métricas agregadas carregadas do Supabase.'}catch(e){$('#supabaseStatus').textContent='ERRO';$('#trafficMsg').className='message error';$('#trafficMsg').textContent='Não foi possível ler o tráfego.'}}
async function loadDbState(){if(!db)return;const checks=[['achievement_catalog','Conquistas'],['milmo_areas','Áreas'],['knowledge_entries','Conhecimento'],['missions','Missões'],['achievement_submissions','Registros aprovados']];const out=[];for(const [t,label] of checks){const {count,error}=await db.from(t).select('*',{count:'exact',head:true});out.push(`<div class="list-item"><strong>${label}</strong><small>${error?'indisponível':Number(count||0).toLocaleString('pt-BR')+' registro(s)'}</small></div>`)}$('#dbState').innerHTML=out.join('')}
function setAgent(name){currentAgent=name;const [tr,ic]=agentInfo[name]||agentInfo['MilMo Guide'];$('#agentName').textContent=name;$('#agentTranslation').textContent=tr;$('#agentIcon').textContent=ic}
$$('[data-agent]').forEach(x=>x.onclick=()=>openAgent(x.dataset.agent));$('#agentFab').onclick=()=>openAgent(currentAgent);function prompts(name){const m={'Mission Agent':['Não encontro o NPC','Não sei onde cavar','Minha missão não avança'],'Island Explorer':['Tokens da ilha','Rhubarb Island','Swamp Island'],'Devourer Hunter':['Próximo marco','World Saver','Onde aparecem?'],'Invader Hunter':['Próximo marco','Meta máxima','Meu progresso'],'Weapon Master':['Marcos das armas','Bow','Onde farmar?'],'Legacy Archivist':['Safir Bow','Cantadeli','CarlãoMooca'],'Rebirth Assistant':['Site oficial','Requisitos','VIP Rebirth']};return m[name]||['Como usar o portal?','Conquistas','MilMoPedia']}
function openAgent(name){currentAgent=name;const [tr,ic]=agentInfo[name]||agentInfo['MilMo Guide'];$('#modalAgentName').textContent=name;$('#modalAgentTranslation').textContent=tr;$('#chat').innerHTML=`<div class="bubble">${ic} Sou <b>${esc(name)}</b> — ${esc(tr)}. Como posso ajudar?</div>`;$('#quick').innerHTML=prompts(name).map(p=>`<button>${esc(p)}</button>`).join('');$$('#quick button').forEach(b=>b.onclick=()=>answerAgent(b.textContent));$('#agentModal').classList.add('on')}
function answerAgent(q){const chat=$('#chat');chat.insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(q)}</div>`);const t=q.toLowerCase();let a='Posso orientar pelo conteúdo já verificado no Hub. Para detalhes ainda não catalogados, o ideal é enviar uma fonte ou prova para não inventarmos informação.';if(t.includes('safir'))a='O Safir Bow está no Arquivo Safir. O Hub registra as provas de Cantadeli no BR e CarlãoMooca no Internacional, mas mantém aberta a busca por outros registros.';else if(t.includes('devor')||t.includes('world'))a='A progressão documentada é 50, 125, 250, 500, 750, 1.500, 3.000 e 5.000. O último marco é World Saver.';else if(t.includes('invad')||t.includes('máxima'))a='A progressão documentada de Invaders é 5, 10, 25, 50, 150, 300, 600 e 1.000. O marco final é The Last Line of Defense.';else if(t.includes('arma')||t.includes('bow')||t.includes('marcos'))a='Os marcos históricos das armas são 150, 300, 600, 1.800, 5.000, 10.000, 25.000 e 50.000 batalhas.';else if(t.includes('token')||t.includes('rhubarb')||t.includes('swamp'))a='Cada área possui normalmente 8 Exploration Tokens. Use a MilMoPedia para marcar os que já encontrou; os guias de localização serão adicionados somente com fonte verificada.';else if(t.includes('rebirth')||t.includes('requisitos')||t.includes('vip'))a='O Rebirth possui site oficial em milmorebirth.com. O VIP atual é um sistema próprio, separado do Membership antigo, e o Hub mantém essa distinção.';else if(t.includes('miss')||t.includes('npc')||t.includes('cavar'))a='O banco de missões está preparado. Como a wiki registra centenas de missões, vamos importar os detalhes por fonte para evitar respostas inventadas. Você pode me dizer o nome exato da missão para pesquisarmos.';chat.insertAdjacentHTML('beforeend',`<div class="bubble">${a}</div>`);chat.scrollTop=chat.scrollHeight}
$('#askAgent').onclick=()=>{const q=$('#agentQuestion').value.trim();if(q){answerAgent(q);$('#agentQuestion').value=''}};$('#agentQuestion').addEventListener('keydown',e=>{if(e.key==='Enter')$('#askAgent').click()});
(async()=>{setAgent('MilMo Guide');await Promise.all([loadCatalog(),loadAreas(),loadKnowledge(),loadRankings(),loadTraffic(),loadDbState()]);track('inicio')})();