(()=>{
const U='https://ayfdkemjykhxqirlzbzw.supabase.co',K='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(U,K):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const order=['horizon-brink','horizon-arena','horizon-sanctuary','horizon-landing','horizon-fishermans-retreat'];
const meta={
'horizon-brink':['🌌','A Borda','The Brink'],
'horizon-arena':['⚔️','Arena','Arena'],
'horizon-sanctuary':['👑','O Santuário','The Sanctuary'],
'horizon-landing':['🧭','O Porto','The Landing'],
'horizon-fishermans-retreat':['🎣','Retiro do Pescador',"Fisherman's Retreat"]};
let c={areas:[],missions:[],entities:[],items:[],tokens:[],ach:[],know:[]};
const css=document.createElement('style');css.textContent=`
.horizon-master-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:12px 0}.horizon-master-summary div{padding:11px;border:1px solid var(--line);border-radius:11px;background:#071b2a}.horizon-master-summary b{display:block;font-size:21px;color:var(--gold)}.horizon-master-summary span{font-size:8px;color:var(--muted)}.horizon-master-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.horizon-card{border:1px solid var(--line);border-radius:14px;padding:13px;background:linear-gradient(145deg,#11283c,#071a28)}.horizon-card h4{margin:6px 0 2px}.horizon-mini{display:grid;grid-template-columns:repeat(3,1fr);gap:4px;margin:8px 0}.horizon-mini div{padding:6px;border:1px solid var(--line);border-radius:7px;background:#061827}.horizon-mini small{display:block;font-size:7px;color:var(--muted)}.sanctuary-layout{display:grid;grid-template-columns:.9fr 1.1fr;gap:13px}.sanctuary-token-list{display:grid;gap:7px}.sanctuary-token{display:grid;grid-template-columns:34px 1fr;gap:9px;padding:9px;border:1px solid var(--line);border-radius:10px;background:#061827}.sanctuary-token .n{display:grid;place-items:center;width:30px;height:30px;border-radius:50%;background:rgba(255,213,74,.1);color:var(--gold);font-weight:900}.arena-ladders{display:grid;grid-template-columns:1fr 1fr;gap:12px}.arena-ladder{border:1px solid var(--line);border-radius:13px;padding:13px;background:#071b2a}.arena-step{display:grid;grid-template-columns:1fr auto;gap:8px;padding:8px 0;border-bottom:1px solid var(--line)}.arena-step:last-child{border-bottom:0}.arena-step b{font-size:10px}.arena-step span{color:var(--gold);font-size:9px}.horizon-note{padding:10px;border-left:3px solid var(--gold);background:rgba(255,213,74,.05);border-radius:0 10px 10px 0;font-size:10px}.horizon-modal .modalbox{width:min(980px,96vw)}.horizon-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}.horizon-sec{border:1px solid var(--line);border-radius:13px;padding:13px;background:#071b2a}.horizon-row{padding:7px 0;border-bottom:1px solid var(--line);font-size:10px}.horizon-row:last-child{border-bottom:0}.horizon-row small{display:block;color:var(--muted);margin-top:2px}@media(max-width:1000px){.horizon-master-grid{grid-template-columns:repeat(2,1fr)}.horizon-master-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.horizon-master-grid,.sanctuary-layout,.arena-ladders,.horizon-cols{grid-template-columns:1fr}.horizon-master-summary{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(css);
function local(slug){try{return JSON.parse(localStorage.getItem('tokens_'+slug)||'[]')}catch{return[]}}
async function load(){if(!db)return;const [a,m,g,i,t,h,k]=await Promise.all([
 db.from('milmo_areas').select('slug,name,description,source_url').eq('adventure','The Horizon'),
 db.from('missions').select('area_slug,title,npc,objective,reward,source_url').like('area_slug','horizon-%').order('title'),
 db.from('game_entities').select('area_slug,name,name_pt,entity_type,amount,spawn_probability,spawn_interval_seconds,notes,source_url').like('area_slug','horizon-%').eq('status','approved').order('name'),
 db.from('game_items').select('area_slug,name,name_pt,location_hint,probability,spawn_interval_seconds,notes,source_url').like('area_slug','horizon-%').eq('status','approved').order('name'),
 db.from('exploration_tokens').select('area_slug,token_no,hint,source_url').like('area_slug','horizon-%').order('token_no'),
 db.from('achievement_catalog').select('slug,title,category,description,target_value,unit,rarity,source_url').like('slug','horizon-%').order('target_value'),
 db.from('knowledge_entries').select('section,title,content,source_url').like('section','area:horizon-%').eq('status','approved').order('title')
]);c={areas:a.data||[],missions:m.data||[],entities:g.data||[],items:i.data||[],tokens:t.data||[],ach:h.data||[],know:k.data||[]};render();}
function render(){const areasWithData=order.filter(s=>c.missions.some(x=>x.area_slug===s)||c.entities.some(x=>x.area_slug===s)||c.items.some(x=>x.area_slug===s)||c.tokens.some(x=>x.area_slug===s)).length;$('#horizonSummary').innerHTML=`<div><b>${areasWithData}/5</b><span>Áreas com conteúdo</span></div><div><b>${c.missions.length}</b><span>Missões catalogadas</span></div><div><b>${c.entities.length}</b><span>NPCs/criaturas/objetos</span></div><div><b>${c.tokens.length}</b><span>Posições exatas de tokens</span></div><div><b>${c.ach.length}</b><span>Medalhas e marcos</span></div>`;$('#horizonGrid').innerHTML=order.map(s=>card(s)).join('');$$('[data-horizon-detail]').forEach(b=>b.onclick=()=>openArea(b.dataset.horizonDetail));renderSanctuary();renderArena()}
function card(slug){const z=meta[slug],m=c.missions.filter(x=>x.area_slug===slug).length,g=c.entities.filter(x=>x.area_slug===slug).length,t=c.tokens.filter(x=>x.area_slug===slug).length;return `<article class="horizon-card"><span style="font-size:30px">${z[0]}</span><h4>${esc(z[1])}</h4><small class="muted">${esc(z[2])}</small><div class="horizon-mini"><div><small>Missões</small><b>${m}</b></div><div><small>Entidades</small><b>${g}</b></div><div><small>Tokens exatos</small><b>${t}</b></div></div><button class="btn secondary" data-horizon-detail="${slug}">Abrir</button></article>`}
function renderSanctuary(){const rows=c.tokens.filter(x=>x.area_slug==='horizon-sanctuary').sort((a,b)=>a.token_no-b.token_no),ach=c.ach.find(x=>x.slug==='horizon-sanctuary-royal-knight');$('#sanctuaryTokens').innerHTML=rows.map(r=>`<div class="sanctuary-token"><div class="n">${r.token_no}</div><div><b>Token ${r.token_no}</b><small class="muted" style="display:block">${esc(r.hint)}</small></div></div>`).join('');$('#sanctuaryMedal').innerHTML=ach?`<b>🏅 ${esc(ach.title)}</b><p class="muted">${esc(ach.description)}</p><small>Recompensa histórica do guia: Crystal Tiara + 500 XP.</small>`:'<p class="muted">Medalha em validação.</p>'}
function renderArena(){const win=c.ach.filter(x=>['horizon-arena-tenderfoot','horizon-arena-challenger','horizon-arena-rival','horizon-arena-champion'].includes(x.slug)),kill=c.ach.filter(x=>['horizon-arena-rampaging-rookie','horizon-arena-thracian-terror','horizon-arena-stampeding-secutor','horizon-arena-gruesome-gladiator'].includes(x.slug));const row=r=>`<div class="arena-step"><div><b>${esc(r.title)}</b><small class="muted" style="display:block">${esc(r.description)}</small></div><span>${r.target_value??'—'} ${esc(r.unit||'')}</span></div>`;$('#arenaWins').innerHTML=win.map(row).join('');$('#arenaKills').innerHTML=kill.map(row).join('')}
function openArea(slug){const z=meta[slug],a=c.areas.find(x=>x.slug===slug),m=c.missions.filter(x=>x.area_slug===slug),g=c.entities.filter(x=>x.area_slug===slug),i=c.items.filter(x=>x.area_slug===slug),t=c.tokens.filter(x=>x.area_slug===slug),k=c.know.filter(x=>x.section==='area:'+slug);$('#horizonModal').classList.add('on');$('#horizonTitle').textContent=z[0]+' '+z[1];$('#horizonSub').textContent=z[2];$('#horizonBody').innerHTML=`<div class="horizon-cols"><section class="horizon-sec"><h3>📜 Missões (${m.length})</h3>${m.map(r=>`<div class="horizon-row"><b>${esc(r.title)}</b>${r.npc?`<small>NPC: ${esc(r.npc)}</small>`:''}${r.objective?`<small>${esc(r.objective)}</small>`:''}${r.reward?`<small>Recompensa: ${esc(r.reward)}</small>`:''}</div>`).join('')||'<p class="muted">Sem missões individualizadas.</p>'}</section><section class="horizon-sec"><h3>🧑 Entidades (${g.length})</h3>${g.map(r=>`<div class="horizon-row"><b>${esc(r.name_pt||r.name)}</b><small>${esc(r.entity_type)}${r.amount?' • qtd. '+r.amount:''}${r.spawn_probability?' • '+esc(r.spawn_probability):''}</small></div>`).join('')||'<p class="muted">Sem entidades catalogadas.</p>'}</section><section class="horizon-sec"><h3>🎒 Itens (${i.length})</h3>${i.map(r=>`<div class="horizon-row"><b>${esc(r.name_pt||r.name)}</b><small>${esc(r.location_hint||'item')}${r.probability?' • '+esc(r.probability):''}</small></div>`).join('')||'<p class="muted">Sem itens catalogados.</p>'}</section><section class="horizon-sec"><h3>🧭 Tokens exatos (${t.length})</h3>${t.map(r=>`<div class="horizon-row"><b>Token ${r.token_no}</b><small>${esc(r.hint)}</small></div>`).join('')||'<p class="muted">Rota individual ainda não verificada.</p>'}</section></div><section class="horizon-sec" style="margin-top:12px"><h3>📚 Contexto</h3><p class="muted">${esc(a?.description||'')}</p>${k.map(r=>`<div class="horizon-row"><b>${esc(r.title)}</b><small>${esc(r.content)}</small></div>`).join('')}</section>`}
function add(){const p=$('#pedia');if(!p||$('#horizonMasterPanel'))return;const s=document.createElement('section');s.id='horizonMasterPanel';s.className='panel';s.innerHTML=`<div class="section-head"><div><span class="eyebrow">THE HORIZON • PAINEL MESTRE</span><h2>Origem, exploração e Arena</h2><p>Visão consolidada das cinco áreas históricas de The Horizon.</p></div><div class="agent-chip"><span class="ico">🧭</span><div><strong>Horizon Guide</strong><small>Guia de The Horizon</small></div></div></div><div class="horizon-master-summary" id="horizonSummary"></div><div class="horizon-master-grid" id="horizonGrid"></div></section>`;const anchor=$('#horizonPanel')||$('#miceMasterPanel')||$('#airMasterPanel')||p.firstElementChild;p.insertBefore(s,anchor);
const sanc=document.createElement('section');sanc.id='sanctuaryExactPanel';sanc.className='panel';sanc.innerHTML=`<div class="section-head"><div><span class="eyebrow">THE SANCTUARY • GUIA EXATO</span><h2>Royal Knight — 8 posições verificadas</h2><p>O Sanctuary aparece no mapa de The Horizon, mas seu guia de tokens é historicamente classificado em Chat Rooms.</p></div></div><div class="sanctuary-layout"><article class="horizon-sec"><h3>👑 Medalha e acesso</h3><div id="sanctuaryMedal"></div><div class="horizon-note" style="margin-top:10px"><b>Sanctuary Key:</b> necessária para entrar no prédio e ter acesso ao interior.</div><a class="link" href="https://milmo.fandom.com/wiki/The_Sanctuary_Tokens" target="_blank" rel="noopener">Fonte dos tokens ↗</a></article><div class="sanctuary-token-list" id="sanctuaryTokens"><p class="muted">Carregando...</p></div></div>`;p.insertBefore(sanc,anchor);
const arena=document.createElement('section');arena.id='horizonArenaPanel';arena.className='panel';arena.innerHTML=`<div class="section-head"><div><span class="eyebrow">ARENA • PvP HISTÓRICO</span><h2>Progressão de vitórias e eliminações</h2><p>Marcos oficiais da Arena separados das medalhas de exploração.</p></div></div><div class="arena-ladders"><article class="arena-ladder"><h3>🏆 Vitórias</h3><div id="arenaWins"></div></article><article class="arena-ladder"><h3>⚔️ Jogadores derrotados</h3><div id="arenaKills"></div></article></div><p style="margin-top:10px"><a class="link" href="https://milmo.fandom.com/wiki/Medals/Arena" target="_blank" rel="noopener">Arquivo completo de medalhas da Arena ↗</a></p>`;p.insertBefore(arena,anchor);
const modal=document.createElement('div');modal.id='horizonModal';modal.className='modal horizon-modal';modal.innerHTML=`<div class="modalbox"><div class="section-head"><div><span class="eyebrow">THE HORIZON • ÁREA</span><h2 id="horizonTitle"></h2><p id="horizonSub" class="muted"></p></div><button class="btn ghost" id="horizonClose">Fechar</button></div><div id="horizonBody"></div></div>`;document.body.appendChild(modal);$('#horizonClose').onclick=()=>modal.classList.remove('on');modal.onclick=ev=>{if(ev.target===modal)modal.classList.remove('on')};load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();