(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],e=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const medals={
 air:[['air-propylon','Head in the Clouds'],['air-mezzanine','Close to the Sun'],['air-palaestra','Gladiator'],['air-necropolis','The Undead'],['air-temenos','The Tranquil'],['air-aviary','Wingless Wonder'],['air-ziggurat','Archaeologist'],['air-village','Villager'],['air-teichos','Wall Guard'],['air-pyrgos','Tower Climber'],['air-ejekatl','Windy Warrior']],
 mice:[['mice-spooky-island','Demolisher'],['mice-refuge','Refugee'],['mice-crawlspace','Claustrophobic'],['mice-flea-circus','Daredevil'],['mice-kitchen','Master Chef'],['mice-living-room','Robot Chew Toy']]
};
const aviaryTokens=[
'Após usar o primeiro canhão, siga o caminho à esquerda; o token fica no topo de um prédio vermelho.',
'Após o primeiro canhão, siga em frente; à esquerda da ponte com blocos vermelhos e azuis, use os blocos azuis móveis.',
'Após o primeiro canhão, siga o caminho à esquerda, pegue o bônus de salto sob a árvore e use-o para subir.',
'Após o segundo canhão, siga em direção ao terceiro; entre três árvores usadas como plataformas, o token fica sob a primeira.',
'Na plataforma inicial com Sentinel 7, no topo da árvore; use poção de salto ou suba pelo canhão e salte do segundo andar.',
'Ao lado de Aurax, no andar superior.',
'Após o primeiro canhão, use a plataforma prateada para alcançar a plataforma onde fica o Parvulu Egg.',
'Atrás da estátua de War Bird próxima ao primeiro canhão.'
];
const zigQuests=['A Tragic Scene','Aurax Repairs','Decisions','Mystical Flames','Not Really Stealing','Temple Invasion','The Forbidden Path','The Power of Wind, Chapter 2','The Power of Wind, Chapter 3','The Power of Wind, Chapter 4','The Power of Wind, Chapter 5','The Power of Wind, Chapter 6','The Power of Wind, Chapter 7','The Power of Wind, Chapter 8'];
const zigItems=[['Fleet Footed','~100% • 15 s'],['Super Jump','~100% • 10 s'],['Golden Statue','~100% • 10 s'],['Blue Ziggurat Key','~100% • 45 s'],['Green Ziggurat Key','~100% • 45 s'],['Red Ziggurat Key','~100% • 45 s'],['Rope','~100% • 3 s']];
const css=document.createElement('style');css.textContent=`.zig-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.zig-card{border:1px solid var(--line);border-radius:16px;padding:16px;background:#071b2a}.zig-card h3{margin:7px 0}.zig-quests{display:grid;grid-template-columns:1fr 1fr;gap:7px}.zig-q{padding:9px;border:1px solid var(--line);border-radius:9px;background:#061827;font-size:10px}.zig-q b{display:block;color:#fff}.zig-items{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.zig-item{padding:9px;border:1px solid var(--line);border-radius:10px;background:#061827}.zig-item b{display:block;color:var(--gold);font-size:10px}.zig-item small{color:var(--muted);font-size:8px}.medal-worlds{display:grid;grid-template-columns:1fr 1fr;gap:14px}.medal-world{border:1px solid var(--line);border-radius:16px;padding:15px;background:#071b2a}.medal-list{display:grid;gap:7px}.medal-row{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:9px 10px;border:1px solid var(--line);border-radius:10px;background:#061827}.medal-row b{font-size:11px}.medal-row small{display:block;color:var(--muted);font-size:8px}.medal-row .done{color:var(--green);font-weight:900;font-size:9px}.medal-row .todo{color:#8197a8;font-size:9px}.aviary-tip{padding:10px;border-left:3px solid var(--gold);background:rgba(255,213,74,.05);border-radius:0 10px 10px 0;font-size:10px}.pala-key{display:grid;grid-template-columns:60px 1fr auto;gap:12px;align-items:center;padding:14px;border:1px solid rgba(176,131,255,.27);border-radius:14px;background:rgba(176,131,255,.05)}.pala-key .ico{font-size:34px;text-align:center}@media(max-width:800px){.zig-grid,.medal-worlds{grid-template-columns:1fr}.zig-quests{grid-template-columns:1fr}.pala-key{grid-template-columns:48px 1fr}.pala-key>a{grid-column:1/-1}.zig-items{grid-template-columns:1fr}}`;document.head.appendChild(css);
function tokenState(area){try{return JSON.parse(localStorage.getItem('tokens_'+area)||'[]')}catch{return[]}}
function addAviaryButton(){const box=$('#verifiedAirTokensPanel .token-area-select');if(!box||$('#aviaryTokenButton'))return;const note=box.querySelector('.token-complete-note');const b=document.createElement('button');b.id='aviaryTokenButton';b.dataset.tokenZone='air-aviary';b.innerHTML='🪽 Aviário <small class="muted" style="display:block">8/8 posições verificadas</small>';b.onclick=()=>{$$('[data-token-zone]').forEach(x=>x.classList.remove('on'));b.classList.add('on');$('#exactTokenList').innerHTML=aviaryTokens.map((x,i)=>`<div class="exact-token"><div class="n">${i+1}</div><div><b>Token ${i+1}</b><p class="muted" style="margin:4px 0 0">${e(x)}</p></div><div class="coord">verificado</div></div>`).join('')+`<div class="aviary-tip"><b>Wingless Wonder:</b> completar os 8 tokens do Aviário concede 1 Sun Token e 2.500 XP.</div><p><a class="link" href="https://milmo.fandom.com/wiki/Aviary_Tokens" target="_blank" rel="noopener">Guia-fonte Aviary Tokens ↗</a></p>`};box.insertBefore(b,note)}
function renderMedalRows(list){return list.map(([area,title])=>{const done=tokenState(area).length===8;return `<div class="medal-row"><div><b>${e(title)}</b><small>${e(area.replaceAll('-',' '))}</small></div><span class="${done?'done':'todo'}">${done?'✓ CONCLUÍDA':'parcial'}</span></div>`}).join('')}
function addPanels(){const p=$('#pedia');if(!p||$('#zigguratPanel'))return;const anchor=$('#questArchivePanel')||$('#adventureHubPanel')||p.lastElementChild;const z=document.createElement('section');z.id='zigguratPanel';z.className='panel';z.innerHTML=`<div class="section-head"><div><span class="eyebrow">MUNDO AÉREO • ÁREA COMPLETA</span><h2>Ziggurat</h2><p>Nível 10, 14 missões catalogadas e itens de progressão do templo das War Birds.</p></div><span class="tag gold">Archaeologist</span></div><div class="zig-grid"><article class="zig-card"><h3>📜 Missões verificadas</h3><div class="zig-quests">${zigQuests.map(x=>`<div class="zig-q"><b>${e(x)}</b></div>`).join('')}</div><p style="margin-top:10px"><a class="link" href="https://milmo.fandom.com/wiki/Ziggurat" target="_blank" rel="noopener">Fonte Ziggurat ↗</a></p></article><article class="zig-card"><h3>🎒 Itens no chão</h3><div class="zig-items">${zigItems.map(x=>`<div class="zig-item"><b>${e(x[0])}</b><small>${e(x[1])}</small></div>`).join('')}</div><div class="callout" style="margin-top:10px"><b>The Forbidden Path:</b> precisa ser concluída para liberar o caminho de Ziggurat até The Village.</div></article></div>`;p.insertBefore(z,anchor);
const pk=document.createElement('section');pk.id='palaestraKeyPanel';pk.className='panel';pk.innerHTML=`<div class="section-head"><div><span class="eyebrow">PALAESTRA</span><h2>Primeiro item-chave verificado</h2></div></div><div class="pala-key"><div class="ico">🔑</div><div><b>Chave Vermelha de Palaestra</b><p class="muted">Recompensa da missão <i>Into the Arena</i>. É usada para ativar a plataforma vermelha de Palaestra.</p></div><a class="btn secondary" href="https://milmo.fandom.com/wiki/Red_Palaestra_Key" target="_blank" rel="noopener">Fonte ↗</a></div>`;p.insertBefore(pk,anchor);
const m=document.createElement('section');m.id='explorationMedalsPanel';m.className='panel';m.innerHTML=`<div class="section-head"><div><span class="eyebrow">MEDALHAS DE EXPLORAÇÃO</span><h2>Mundo Aéreo + Ratos e Maníacos</h2><p>O título aparece concluído quando o checklist local chega a 8/8.</p></div></div><div class="medal-worlds"><article class="medal-world"><h3>☁️ Mundo Aéreo</h3><div class="medal-list">${renderMedalRows(medals.air)}</div></article><article class="medal-world"><h3>🐭 Ratos e Maníacos</h3><div class="medal-list">${renderMedalRows(medals.mice)}</div></article></div>`;p.insertBefore(m,anchor)}
function boot(){addPanels();addAviaryButton();let n=0;const t=setInterval(()=>{addAviaryButton();if(++n>14||$('#aviaryTokenButton'))clearInterval(t)},350)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();