(()=>{
const SURL='https://ayfdkemjykhxqirlzbzw.supabase.co',SKEY='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db7=window.supabase?.createClient?window.supabase.createClient(SURL,SKEY):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const names={'air-labyrinth':'Labirinto','air-propylon':'Propylon','air-atrium':'Atrium','air-mezzanine':'Mezzanine','air-mechalon':'Mechalon','air-palaestra':'Palaestra','air-necropolis':'Necropolis','air-temenos':'Temenos','air-aviary':'Aviário','air-ziggurat':'Ziggurat','air-village':'A Vila','air-teichos':'Teichos','air-pyrgos':'Pyrgos','air-ainigma':'Ainigma','air-ejekatl':'Ejekatl','mice-spooky-island':'Ilha do Medo','mice-refuge':'O Refúgio','mice-crawlspace':'Sob o Assoalho','mice-flea-circus':'Circo de Pulgas','mice-kitchen':'Cozinha','mice-living-room':'Sala de Estar'};
let airMissions=[],miceMissions=[],tokenRows=[];
const css=document.createElement('style');css.textContent=`
.quest-archive-tools{display:grid;grid-template-columns:1fr auto auto;gap:8px;margin-bottom:13px}.quest-archive-tools input{width:100%;padding:10px;border:1px solid var(--line);border-radius:10px;background:#061827;color:#fff}.quest-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:11px 0}.quest-stats div{padding:11px;border:1px solid var(--line);border-radius:11px;background:#071b2a}.quest-stats b{display:block;font-size:20px;color:var(--gold)}.quest-stats span{font-size:9px;color:var(--muted)}.quest-groups{display:grid;gap:10px}.quest-group{border:1px solid var(--line);border-radius:14px;background:#071b2a;overflow:hidden}.quest-group-head{display:flex;justify-content:space-between;gap:10px;padding:12px 14px;background:#09243a;border-bottom:1px solid var(--line)}.quest-group-head b{color:var(--gold)}.quest-list{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;padding:10px}.quest-card{padding:10px;border:1px solid var(--line);border-radius:10px;background:#061827}.quest-card b{display:block;font-size:11px}.quest-card small{display:block;color:var(--muted);font-size:9px;margin-top:3px}.quest-card p{font-size:10px;margin:6px 0;color:#cbdbe6}.verified-token-panel{display:grid;grid-template-columns:300px 1fr;gap:14px}.token-area-select{display:grid;gap:8px}.token-area-select button{padding:12px;text-align:left;border:1px solid var(--line);border-radius:11px;background:#071b2a;color:#fff}.token-area-select button.on{border-color:rgba(255,213,74,.5);background:rgba(255,213,74,.08)}.exact-token-list{display:grid;gap:8px}.exact-token{display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:start;padding:11px;border:1px solid var(--line);border-radius:11px;background:#061827}.exact-token .n{display:grid;place-items:center;width:34px;height:34px;border-radius:50%;background:rgba(66,201,255,.12);color:var(--blue);font-weight:900}.exact-token .coord{font-size:9px;color:var(--gold);white-space:nowrap}.token-complete-note{padding:12px;border-left:4px solid var(--green);background:rgba(139,237,119,.06);border-radius:0 12px 12px 0}.air-boss-card{display:grid;grid-template-columns:80px 1fr auto;gap:14px;align-items:center;padding:16px;border:1px solid rgba(255,213,74,.28);border-radius:15px;background:linear-gradient(145deg,rgba(255,213,74,.06),rgba(6,24,39,.9))}.air-boss-card .boss-emoji{font-size:48px;text-align:center}.air-boss-card b{color:var(--gold)}.mice-heart{display:grid;grid-template-columns:90px 1fr;gap:15px;align-items:center;padding:17px;border:1px solid rgba(176,131,255,.28);border-radius:15px;background:rgba(176,131,255,.055)}.mice-heart .heart{font-size:54px;text-align:center}@media(max-width:800px){.quest-list{grid-template-columns:1fr}.verified-token-panel{grid-template-columns:1fr}.quest-stats{grid-template-columns:1fr 1fr}.quest-archive-tools{grid-template-columns:1fr}.air-boss-card{grid-template-columns:60px 1fr}.air-boss-card>a{grid-column:1/-1}.mice-heart{grid-template-columns:60px 1fr}}`;
document.head.appendChild(css);
let mode='air',tokenArea='air-propylon';
function inject(){const p=$('#pedia');if(!p||$('#questArchivePanel'))return;
const tok=document.createElement('section');tok.id='verifiedAirTokensPanel';tok.className='panel';tok.innerHTML=`<div class="section-head"><div><span class="eyebrow">GUIAS DE TOKENS VERIFICADOS</span><h2>Posições reais — Mundo Aéreo</h2><p>Primeiras áreas com localização individual dos 8 tokens documentada no banco.</p></div><div class="agent-chip" id="tokenAgent"><span class="ico">☀️</span><div><strong>Air World Guide</strong><small>Guia do Mundo Aéreo</small></div></div></div><div class="verified-token-panel"><div class="token-area-select"><button class="on" data-token-zone="air-propylon">☁️ Propylon <small class="muted" style="display:block">8/8 posições verificadas</small></button><button data-token-zone="air-atrium">🏛️ Atrium <small class="muted" style="display:block">8/8 posições verificadas</small></button><div class="token-complete-note"><b>Regra do Air World</b><br><small>8 Exploration Tokens → 1 Sun Token → fale com Aurax para continuar.</small></div></div><div><div class="exact-token-list" id="exactTokenList"><p class="muted">Carregando...</p></div></div></div>`;
const anchor=$('#adventureHubPanel')||$('#itemsPanel')||$('#bestiaryPanel')||p.lastElementChild;p.insertBefore(tok,anchor);
const q=document.createElement('section');q.id='questArchivePanel';q.className='panel';q.innerHTML=`<div class="section-head"><div><span class="eyebrow">ARQUIVO DE MISSÕES</span><h2>Mundo Aéreo + Ratos e Maníacos</h2><p>Missões adicionadas somente quando o vínculo com a área está documentado.</p></div><div class="agent-chip" id="questAgent"><span class="ico">🧭</span><div><strong>Mission Agent</strong><small>Agente de Missões</small></div></div></div><div class="quest-stats" id="questStats"></div><div class="quest-archive-tools"><input id="questArchiveSearch" placeholder="Pesquisar missão, NPC ou objetivo..."><button class="btn secondary" id="questAir">☁️ Mundo Aéreo</button><button class="btn secondary" id="questMice">🐭 Ratos e Maníacos</button></div><div class="quest-groups" id="questGroups"><p class="muted">Carregando missões...</p></div>`;p.insertBefore(q,anchor);
const boss=document.createElement('section');boss.id='airBossFeature';boss.className='panel';boss.innerHTML=`<div class="section-head"><div><span class="eyebrow">CHEFE DO MUNDO AÉREO</span><h2>O Mechalon</h2></div></div><div class="air-boss-card"><div class="boss-emoji">🤖</div><div><b>The Mechalon</b><p class="muted">Mechalon exige nível 8. O chefe é o único monstro normal da área, reaparece em cerca de 60 segundos e é obrigatório para avançar até o final da aventura.</p><small class="muted">NPCs registrados na área: Sentinel 7 e Aurax.</small></div><a class="btn secondary" href="https://milmo.fandom.com/wiki/Mechalon" target="_blank" rel="noopener">Fonte ↗</a></div>`;p.insertBefore(boss,anchor);
const heart=document.createElement('section');heart.id='miceHeartFeature';heart.className='panel';heart.innerHTML=`<div class="section-head"><div><span class="eyebrow">EXPLORAÇÃO DE RATOS E MANÍACOS</span><h2>Heroic Heart</h2></div></div><div class="mice-heart"><div class="heart">💜</div><div><b>Os tokens têm outra função aqui.</b><p class="muted">Em Mice & Maniax, completar os Exploration Tokens fornece itens usados para montar a habilidade especial Heroic Heart. Por isso, o Hub mantém o progresso de tokens separado do sistema de Sun Tokens do Air World.</p><a class="link" href="https://milmo.fandom.com/wiki/Exploration_Tokens" target="_blank" rel="noopener">Fonte ↗</a></div></div>`;p.insertBefore(heart,anchor);
$('#tokenAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent('Air World Guide')}catch{}};$('#questAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent('Mission Agent')}catch{}};$$('[data-token-zone]').forEach(b=>b.onclick=()=>{tokenArea=b.dataset.tokenZone;$$('[data-token-zone]').forEach(x=>x.classList.toggle('on',x===b));renderTokens()});$('#questArchiveSearch').addEventListener('input',renderQuests);$('#questAir').onclick=()=>{mode='air';$('#questArchiveSearch').value='';renderQuests()};$('#questMice').onclick=()=>{mode='mice';$('#questArchiveSearch').value='';renderQuests()};load();}
async function load(){if(!db7)return;const [air,mice,tokens]=await Promise.all([db7.from('missions').select('title,area_slug,npc,objective,reward,source_url').like('area_slug','air-%').order('area_slug').order('title'),db7.from('missions').select('title,area_slug,npc,objective,reward,source_url').like('area_slug','mice-%').order('area_slug').order('title'),db7.from('exploration_tokens').select('area_slug,token_no,hint,coordinates,source_url').in('area_slug',['air-propylon','air-atrium']).order('area_slug').order('token_no')]);airMissions=air.data||[];miceMissions=mice.data||[];tokenRows=tokens.data||[];renderTokens();renderQuests()}
function renderTokens(){const rows=tokenRows.filter(x=>x.area_slug===tokenArea);$('#exactTokenList').innerHTML=rows.length?rows.map(x=>`<div class="exact-token"><div class="n">${x.token_no}</div><div><b>Token ${x.token_no}</b><p class="muted" style="margin:4px 0 0">${esc(x.hint)}</p></div><div class="coord">${esc(x.coordinates||'verificado')}</div></div>`).join(''):'<p class="muted">Sem posições verificadas.</p>'}
function renderQuests(){const all=mode==='air'?airMissions:miceMissions,s=($('#questArchiveSearch')?.value||'').toLowerCase().trim(),list=all.filter(x=>!s||[x.title,x.npc,x.objective,x.reward,names[x.area_slug]].join(' ').toLowerCase().includes(s)),areas=[...new Set(list.map(x=>x.area_slug))];const historical=mode==='air'?95:'—';$('#questStats').innerHTML=`<div><b>${all.length}</b><span>Missões verificadas no banco</span></div><div><b>${areas.length}</b><span>Áreas já com missões</span></div><div><b>${historical}</b><span>${mode==='air'?'Missões históricas da aventura':'Total histórico ainda em validação'}</span></div><div><b>${mode==='air'?'15':'6'}</b><span>Áreas da aventura</span></div>`;$('#questGroups').innerHTML=areas.length?areas.map(a=>{const rows=list.filter(x=>x.area_slug===a);return `<section class="quest-group"><div class="quest-group-head"><b>${esc(names[a]||a)}</b><span class="tag">${rows.length} missão(ões)</span></div><div class="quest-list">${rows.map(x=>`<article class="quest-card"><b>${esc(x.title)}</b>${x.npc?`<small>NPC: ${esc(x.npc)}</small>`:''}${x.objective?`<p>${esc(x.objective)}</p>`:''}${x.reward?`<small>Recompensa: ${esc(x.reward)}</small>`:''}${x.source_url?`<a class="link" href="${esc(x.source_url)}" target="_blank" rel="noopener">fonte ↗</a>`:''}</article>`).join('')}</div></section>`}).join(''):'<p class="muted">Nenhuma missão encontrada.</p>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();