(()=>{
const U='https://ayfdkemjykhxqirlzbzw.supabase.co',K='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(U,K):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const PT={
'air-labyrinth':'Labirinto','air-propylon':'Propylon','air-atrium':'Atrium','air-mezzanine':'Mezzanine','air-mechalon':'Mechalon','air-palaestra':'Palaestra','air-necropolis':'Necropolis','air-temenos':'Temenos','air-aviary':'Aviário','air-ziggurat':'Ziggurat','air-village':'A Vila','air-teichos':'Teichos','air-pyrgos':'Pyrgos','air-ainigma':'Ainigma','air-ejekatl':'Ejekatl',
'mice-spooky-island':'Ilha do Medo','mice-refuge':'O Refúgio','mice-crawlspace':'Sob o Assoalho','mice-flea-circus':'Circo de Pulgas','mice-kitchen':'Cozinha','mice-living-room':'Sala de Estar'};
const css=document.createElement('style');css.textContent=`
.adventure-hubs{display:grid;grid-template-columns:1fr 1fr;gap:15px}.adv-hub{border:1px solid var(--line);border-radius:20px;padding:20px;background:linear-gradient(145deg,#0b2b42,#071b29);overflow:hidden;position:relative}.adv-hub.air{background:linear-gradient(145deg,#14375a,#0a2035)}.adv-hub.mice{background:linear-gradient(145deg,#2b2338,#121827)}.adv-hub .adv-icon{font-size:44px}.adv-hub h3{margin:8px 0 4px}.adv-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:13px 0}.adv-stats div{padding:10px;border:1px solid var(--line);border-radius:11px;background:rgba(2,12,20,.35)}.adv-stats small{display:block;color:var(--muted);font-size:9px}.adv-stats b{font-size:12px;color:var(--gold)}.adv-world{margin-top:14px}.world-toolbar{display:grid;grid-template-columns:1fr auto auto;gap:8px;margin-bottom:12px}.world-toolbar input{width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#061827;color:#fff}.world-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.world-area{border:1px solid var(--line);border-radius:14px;padding:14px;background:#071b2a}.world-area h4{margin:6px 0 3px}.world-area .en{font-size:10px;color:var(--muted)}.world-area p{font-size:11px;color:#c8d9e5}.world-token-grid{display:grid;grid-template-columns:repeat(8,1fr);gap:4px;margin:9px 0}.world-token-grid button{padding:6px 0;border:1px solid var(--line);border-radius:7px;background:#051521;color:#bcd0dd;font-size:9px}.world-token-grid button.done{background:rgba(139,237,119,.15);color:var(--green);border-color:rgba(139,237,119,.34)}.sun-badge{display:inline-flex;align-items:center;gap:5px;padding:6px 8px;border-radius:999px;background:rgba(255,213,74,.12);border:1px solid rgba(255,213,74,.28);color:var(--gold);font-size:9px;font-weight:800}.sun-badge.off{opacity:.42;filter:grayscale(1)}.adv-notes{display:grid;gap:8px}.adv-note{padding:10px;border:1px solid var(--line);border-radius:10px;background:#061827}.adv-note b{display:block;color:var(--gold);font-size:11px}.adv-note p{font-size:10px;margin:4px 0 0;color:#cbdbe6}.family-row{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.family-row span{padding:6px 8px;border-radius:999px;border:1px solid var(--line);font-size:9px}.world-progress{height:9px;background:#051521;border-radius:999px;overflow:hidden;margin:9px 0}.world-progress i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--green),var(--gold));width:0}.world-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:10px 0}.world-summary div{padding:10px;border:1px solid var(--line);border-radius:10px;background:#061827}.world-summary small{display:block;color:var(--muted);font-size:8px}.world-summary b{font-size:14px;color:var(--gold)}
@media(max-width:1000px){.world-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.adventure-hubs,.world-grid{grid-template-columns:1fr}.world-toolbar{grid-template-columns:1fr}.world-summary{grid-template-columns:1fr 1fr}.adv-stats{grid-template-columns:1fr 1fr}}`;
document.head.appendChild(css);
let data={air:[],mice:[],airKnow:[],miceKnow:[]};
function tok(slug){try{return JSON.parse(localStorage.getItem('tokens_'+slug)||'[]')}catch{return[]}}
function toggle(slug,n){let a=tok(slug);a=a.includes(n)?a.filter(x=>x!==n):[...a,n].sort((x,y)=>x-y);localStorage.setItem('tokens_'+slug,JSON.stringify(a));renderWorlds()}
function inject(){const p=$('#pedia');if(!p||$('#adventureHubPanel'))return;try{if(typeof agentInfo!=='undefined'){agentInfo['Air World Guide']=['Guia do Mundo Aéreo','☁️'];agentInfo['Mice Guide']=['Guia de Ratos e Maníacos','🐭']}}catch{}
const panel=document.createElement('section');panel.id='adventureHubPanel';panel.className='panel';panel.innerHTML=`<div class="section-head"><div><span class="eyebrow">NOVOS MUNDOS NA MILMOPEDIA</span><h2>Mundo Aéreo + Ratos e Maníacos</h2><p>As duas aventuras agora têm estrutura própria, áreas, progresso de exploração e regras específicas.</p></div></div><div class="adventure-hubs"><article class="adv-hub air"><span class="adv-icon">☁️</span><span class="tag">AIR WORLD</span><h3>Mundo Aéreo</h3><p class="muted">Civilização aérea, Aurax, Sun Tokens, estátuas, Parvulu e War Birds.</p><div class="adv-stats"><div><small>Áreas</small><b>15</b></div><div><small>Missões históricas</small><b>95</b></div><div><small>Regra-chave</small><b>8 tokens → Sun Token</b></div></div><button class="btn" id="openAirWorld">Abrir Mundo Aéreo</button></article><article class="adv-hub mice"><span class="adv-icon">🐭</span><span class="tag purple">MICE & MANIAX</span><h3>Ratos e Maníacos</h3><p class="muted">A casa do cientista maluco, resistência dos ratos, fantasmas, insetos e robôs.</p><div class="adv-stats"><div><small>Áreas</small><b>6</b></div><div><small>Exploração</small><b>8 tokens/área</b></div><div><small>Transporte</small><b>Green + carrinho</b></div></div><button class="btn" id="openMiceWorld">Abrir Ratos e Maníacos</button></article></div></section>`;
const anchor=$('#itemsPanel')||$('#bestiaryPanel')||$('#legacyGuidePanel')||$('#deepGuidePanel')||$('#missionHubPanel')||p.lastElementChild;p.insertBefore(panel,anchor);
const world=document.createElement('section');world.id='worldExplorerPanel';world.className='panel';world.innerHTML=`<div class="section-head"><div><span class="eyebrow">EXPLORADOR DE AVENTURAS</span><h2 id="worldTitle">Mundo Aéreo</h2><p id="worldIntro" class="muted"></p></div><div class="agent-chip" id="worldAgent"><span class="ico">🗺️</span><div><strong id="worldAgentName">Air World Guide</strong><small id="worldAgentPt">Guia do Mundo Aéreo</small></div></div></div><div class="world-summary" id="worldSummary"></div><div class="world-progress"><i id="worldProgressBar"></i></div><div class="world-toolbar"><input id="worldSearch" placeholder="Pesquisar área..."><button class="btn secondary" id="showAir">☁️ Mundo Aéreo</button><button class="btn secondary" id="showMice">🐭 Ratos e Maníacos</button></div><div class="adv-notes" id="worldNotes"></div><div class="world-grid adv-world" id="worldGrid"><p class="muted">Carregando áreas...</p></div>`;p.insertBefore(world,anchor);
$('#openAirWorld').onclick=()=>setWorld('air');$('#openMiceWorld').onclick=()=>setWorld('mice');$('#showAir').onclick=()=>setWorld('air');$('#showMice').onclick=()=>setWorld('mice');$('#worldSearch').addEventListener('input',renderWorlds);$('#worldAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent(currentWorld==='air'?'Air World Guide':'Mice Guide')}catch{}};load();}
let currentWorld='air';
async function load(){if(!db)return;const [areas,know]=await Promise.all([db.from('milmo_areas').select('slug,name,adventure,description,source_url').in('adventure',['Air World','Mice & Maniax']).order('name'),db.from('knowledge_entries').select('section,title,content,source_url').in('section',['adventure:air-world','adventure:mice-maniax']).eq('status','approved').order('title')]);const rows=areas.data||[];data.air=rows.filter(x=>x.adventure==='Air World');data.mice=rows.filter(x=>x.adventure==='Mice & Maniax');const k=know.data||[];data.airKnow=k.filter(x=>x.section==='adventure:air-world');data.miceKnow=k.filter(x=>x.section==='adventure:mice-maniax');setWorld('air')}
function setWorld(w){currentWorld=w;$('#worldSearch').value='';const air=w==='air';$('#worldTitle').textContent=air?'☁️ Mundo Aéreo':'🐭 Ratos e Maníacos';$('#worldIntro').textContent=air?'Complete os 8 Exploration Tokens de cada área para registrar seu Sun Token localmente.':'Explore as seis áreas da casa do cientista maluco e acompanhe seus tokens por área.';$('#worldAgentName').textContent=air?'Air World Guide':'Mice Guide';$('#worldAgentPt').textContent=air?'Guia do Mundo Aéreo':'Guia de Ratos e Maníacos';renderWorlds()}
function renderWorlds(){const list=currentWorld==='air'?data.air:data.mice,know=currentWorld==='air'?data.airKnow:data.miceKnow;const s=($('#worldSearch')?.value||'').toLowerCase().trim();const filtered=list.filter(x=>!s||[x.name,PT[x.slug],x.description].join(' ').toLowerCase().includes(s));const complete=list.filter(x=>tok(x.slug).length===8).length,totalTokens=list.reduce((a,x)=>a+tok(x.slug).length,0),max=list.length*8,pct=max?totalTokens/max*100:0;$('#worldSummary').innerHTML=`<div><small>Áreas</small><b>${list.length}</b></div><div><small>Tokens marcados</small><b>${totalTokens}/${max}</b></div><div><small>Áreas 8/8</small><b>${complete}/${list.length}</b></div><div><small>${currentWorld==='air'?'Sun Tokens locais':'Progresso'}</small><b>${currentWorld==='air'?complete:Math.round(pct)+'%'}</b></div>`;$('#worldProgressBar').style.width=pct+'%';$('#worldNotes').innerHTML=know.map(k=>`<div class="adv-note"><b>${esc(k.title)}</b><p>${esc(k.content)} ${k.source_url?`<a class="link" href="${esc(k.source_url)}" target="_blank" rel="noopener">fonte ↗</a>`:''}</p></div>`).join('');$('#worldGrid').innerHTML=filtered.length?filtered.map(x=>areaCard(x)).join(''):'<p class="muted">Nenhuma área encontrada.</p>';$$('[data-world-token]').forEach(b=>b.onclick=()=>toggle(b.dataset.area,Number(b.dataset.worldToken)))}
function areaCard(x){const t=tok(x.slug),done=t.length===8,air=x.adventure==='Air World';return `<article class="world-area"><span class="tag ${air?'':'purple'}">${air?'AIR WORLD':'MICE & MANIAX'}</span><h4>${esc(PT[x.slug]||x.name)}</h4>${PT[x.slug]&&PT[x.slug]!==x.name?`<div class="en">${esc(x.name)}</div>`:''}<p>${esc(x.description||'Área catalogada.')}</p><div class="world-token-grid">${Array.from({length:8},(_,i)=>`<button class="${t.includes(i+1)?'done':''}" data-area="${esc(x.slug)}" data-world-token="${i+1}">${i+1}</button>`).join('')}</div><div class="row" style="align-items:center;justify-content:space-between"><small class="muted">${t.length}/8 tokens</small>${air?`<span class="sun-badge ${done?'':'off'}">☀️ ${done?'Sun Token obtido':'Sun Token pendente'}</span>`:done?'<span class="sun-badge">✓ Área completa</span>':''}</div>${x.source_url?`<p style="margin-top:9px"><a class="link" href="${esc(x.source_url)}" target="_blank" rel="noopener">Fonte da área ↗</a></p>`:''}</article>`}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();