(()=>{
const U='https://ayfdkemjykhxqirlzbzw.supabase.co',K='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(U,K):null,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const focus=['sts-boss-beach','sts-treehouse-island','sts-alien-ruins','sts-yacht','sts-eternal-monument','sts-dunes'];
const meta={
'sts-boss-beach':['👾','Boss Beach','sem tokens por regra do jogo'],
'sts-treehouse-island':['🌳','Treehouse Island','8/8 tokens exatos'],
'sts-alien-ruins':['👽','Alien Ruins','itens e objetos narrativos'],
'sts-yacht':['🛥️','Yacht','chat room premium'],
'sts-eternal-monument':['🗿','The Eternal Monument','Infiltrator'],
'sts-dunes':['🏜️','The Dunes','Caravaneer']};
const css=document.createElement('style');css.textContent=`
.sts-wave3{margin:12px 0;padding:13px;border:1px solid rgba(139,237,119,.24);border-radius:13px;background:linear-gradient(145deg,#0b2a25,#071722)}.sts-wave3-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.sts-wave3-card{padding:11px;border:1px solid var(--line);border-radius:11px;background:#061827}.sts-wave3-card h4{margin:5px 0 1px}.sts-wave3-mini{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin:7px 0}.sts-wave3-mini div{padding:5px;border:1px solid var(--line);border-radius:7px;text-align:center}.sts-wave3-mini b{display:block;font-size:9px}.sts-wave3-mini small{font-size:6px;color:var(--muted)}.sts-complete{margin-top:10px;padding:10px;border-left:3px solid var(--green);background:rgba(139,237,119,.06);border-radius:0 9px 9px 0;font-size:10px}.sts-complete b{color:var(--green)}@media(max-width:800px){.sts-wave3-grid{grid-template-columns:1fr}}
`;document.head.appendChild(css);
let rows=[];
async function load(){if(!db)return;const [a,m,i,g,t]=await Promise.all([db.from('milmo_areas').select('slug,name').in('slug',focus),db.from('missions').select('area_slug').in('area_slug',focus),db.from('game_items').select('area_slug').in('area_slug',focus).eq('status','approved'),db.from('game_entities').select('area_slug').in('area_slug',focus).eq('status','approved'),db.from('exploration_tokens').select('area_slug').in('area_slug',focus)]);rows=(a.data||[]).map(x=>({slug:x.slug,m:(m.data||[]).filter(r=>r.area_slug===x.slug).length,i:(i.data||[]).filter(r=>r.area_slug===x.slug).length,g:(g.data||[]).filter(r=>r.area_slug===x.slug).length,t:(t.data||[]).filter(r=>r.area_slug===x.slug).length}));mount()}
function jump(slug){const tab=$$('[data-mp-adv]').find(x=>x.dataset.mpAdv==='Summer Tide Saga');if(tab)tab.click();const s=$('#mpSearch');if(s){s.value=meta[slug][1];s.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(()=>s.scrollIntoView({behavior:'smooth',block:'center'}),50)}}
function mount(){const nav=$('#milmoPediaNavigator');if(!nav||$('#stsWave3')||!rows.length)return;const anchor=$('#stsWave2')||$('#stsCoverageStrip')||$('#mpTabs');const box=document.createElement('div');box.id='stsWave3';box.className='sts-wave3';box.innerHTML=`<div class="section-head" style="margin:0"><div><span class="eyebrow">SUMMER TIDE • ONDA 3</span><h3 style="margin:3px 0">Cobertura base fechada nas 21 áreas</h3><p class="muted" style="margin:0">A última leva preenche Boss Beach, Treehouse Island, Alien Ruins, Yacht, Eternal Monument e The Dunes.</p></div><span class="tag green">21/21 áreas com conteúdo</span></div><div class="sts-wave3-grid">${focus.map(slug=>{const r=rows.find(x=>x.slug===slug)||{m:0,i:0,g:0,t:0},z=meta[slug];return `<article class="sts-wave3-card"><span style="font-size:26px">${z[0]}</span><h4>${z[1]}</h4><small class="muted">${z[2]}</small><div class="sts-wave3-mini"><div><b>${r.m}</b><small>MISSÕES</small></div><div><b>${r.g}</b><small>ENTIDADES</small></div><div><b>${r.i}</b><small>ITENS</small></div><div><b>${r.t}</b><small>TOKENS</small></div></div><button class="btn secondary" data-sts3="${slug}">Abrir no navegador</button></article>`}).join('')}</div><div class="sts-complete"><b>Summer Tide Saga agora tem cobertura básica em todas as 21 áreas.</b> Boss Beach aparece corretamente com 0 tokens porque é a única área do jogo sem Exploration Tokens. Treehouse Island já tem a rota completa 8/8 documentada.</div>`;anchor.after(box);$$('[data-sts3]').forEach(b=>b.onclick=()=>jump(b.dataset.sts3))}
function boot(){let n=0;const t=setInterval(()=>{if($('#milmoPediaNavigator')){clearInterval(t);load()}else if(++n>30)clearInterval(t)},250)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();