(()=>{
const URL='https://ayfdkemjykhxqirlzbzw.supabase.co',KEY='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db4=window.supabase?.createClient?window.supabase.createClient(URL,KEY):null;
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)],h=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let entities=[];
const areaNames={'kraken-island':'Ilha do Kraken','visitor-island':'Ilha dos Visitantes','ancient-forest':'Floresta Antiga','hidden-tor':'The Hidden Tor','rhubarb-island':'Ilha Ruibarbo','swamp-island':'Ilha do Pântano'};
const typeNames={boss:'Chefe',monster:'Monstro',creature:'Criatura',resource:'Recurso',npc:'NPC',object:'Objeto'};
const icon={boss:'👑',monster:'⚔️',creature:'🦋',resource:'⛏️',npc:'🧑',object:'📦'};
const css=document.createElement('style');css.textContent=`
.bestiary-tools{display:grid;grid-template-columns:1fr 180px 190px auto;gap:8px;margin-bottom:14px}.bestiary-tools input,.bestiary-tools select{width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#061827;color:#fff}.bestiary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.beast-card{border:1px solid var(--line);border-radius:15px;padding:15px;background:linear-gradient(145deg,#0a2438,#061824)}.beast-card .beast-icon{font-size:30px}.beast-card h3{margin:7px 0 2px}.beast-card .pt{font-size:11px;color:var(--muted)}.beast-meta{display:flex;gap:5px;flex-wrap:wrap;margin:9px 0}.beast-meta span{padding:5px 7px;border-radius:999px;border:1px solid var(--line);font-size:9px;color:#c5d6e1}.beast-spawn{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin:10px 0}.beast-spawn div{background:#051522;border:1px solid var(--line);border-radius:9px;padding:7px}.beast-spawn small{display:block;color:var(--muted);font-size:8px}.beast-spawn b{font-size:10px;color:var(--gold)}.bestiary-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:12px 0}.bestiary-summary div{padding:12px;border:1px solid var(--line);border-radius:12px;background:#071b2a}.bestiary-summary b{display:block;font-size:24px;color:var(--gold)}.bestiary-summary span{font-size:9px;color:var(--muted)}.boss-highlight{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.boss-highlight article{border:1px solid rgba(255,213,74,.25);background:rgba(255,213,74,.05);padding:15px;border-radius:14px}.boss-highlight b{display:block;color:var(--gold);margin:6px 0}.medal-rule{padding:13px;border-left:4px solid var(--blue);background:rgba(66,201,255,.06);border-radius:0 12px 12px 0}.bestiary-empty{padding:25px;text-align:center;color:var(--muted)}@media(max-width:1000px){.bestiary-grid{grid-template-columns:repeat(2,1fr)}.bestiary-tools{grid-template-columns:1fr 1fr}}@media(max-width:700px){.bestiary-grid,.boss-highlight{grid-template-columns:1fr}.bestiary-summary{grid-template-columns:1fr 1fr}.bestiary-tools{grid-template-columns:1fr}.beast-spawn{grid-template-columns:1fr 1fr 1fr}}`;
document.head.appendChild(css);
function addAgents(){try{if(typeof agentInfo!=='undefined'){agentInfo['Creature Tracker']=['Rastreador de Criaturas','🦋'];agentInfo['Monster Hunter']=['Caçador de Monstros','⚔️']}}catch{}}
function inject(){const p=qs('#pedia');if(!p||qs('#bestiaryPanel'))return;addAgents();const panel=document.createElement('section');panel.id='bestiaryPanel';panel.className='panel';panel.innerHTML=`<div class="section-head"><div><span class="eyebrow">BESTIÁRIO MILMO</span><h2>Monstros, criaturas e chefes</h2><p>Catálogo verificado por área, com spawn, famílias de medalhas e fontes.</p></div><div class="agent-chip" id="creatureAgent"><span class="ico">🦋</span><div><strong>Creature Tracker</strong><small>Rastreador de Criaturas</small></div></div></div><div class="bestiary-summary" id="bestiarySummary"><div><b>—</b><span>Entidades</span></div><div><b>—</b><span>Monstros</span></div><div><b>—</b><span>Criaturas</span></div><div><b>—</b><span>Chefes</span></div></div><div class="bestiary-tools"><input id="beastSearch" placeholder="Pesquisar: Alien Bug, Snail, Skull..."><select id="beastType"><option value="">Todos os tipos</option><option value="boss">Chefes</option><option value="monster">Monstros</option><option value="creature">Criaturas</option></select><select id="beastArea"><option value="">Todas as áreas</option></select><button class="btn secondary" id="beastReset">Limpar</button></div><div class="bestiary-grid" id="bestiaryGrid"><div class="bestiary-empty">Carregando Bestiário...</div></div><div class="medal-rule" style="margin-top:15px"><b>Progressão padrão de famílias de monstros:</b> 100 → 250 → 500 → 1.000 → 1.500 → 3.000 → 6.000 → 10.000. <b>Exceções:</b> Devoradores e Invasores usam sequências próprias já mostradas na área Meu Progresso.</div></section>`;const anchor=qs('#legacyGuidePanel')||qs('#deepGuidePanel')||qs('#missionHubPanel')||p.lastElementChild;p.insertBefore(panel,anchor);
const bosses=document.createElement('section');bosses.id='liveBossPanel';bosses.className='panel';bosses.innerHTML=`<div class="section-head"><div><span class="eyebrow">BOSS ARCHIVE • BANCO REAL</span><h2>Chefes verificados</h2><p>Chefes são separados de monstros comuns porque possuem mais vida, ataques próprios e recompensas/progressão específicas.</p></div><div class="agent-chip" id="monsterAgent"><span class="ico">⚔️</span><div><strong>Monster Hunter</strong><small>Caçador de Monstros</small></div></div></div><div class="boss-highlight" id="bossLive"><p class="muted">Carregando...</p></div>`;p.insertBefore(bosses,anchor);
qs('#creatureAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent('Creature Tracker')}catch{}};qs('#monsterAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent('Monster Hunter')}catch{}};
qs('#beastSearch').addEventListener('input',render);qs('#beastType').addEventListener('change',render);qs('#beastArea').addEventListener('change',render);qs('#beastReset').onclick=()=>{qs('#beastSearch').value='';qs('#beastType').value='';qs('#beastArea').value='';render()};load();}
async function load(){if(!db4){qs('#bestiaryGrid').innerHTML='<div class="bestiary-empty">Supabase indisponível.</div>';return}const {data,error}=await db4.from('game_entities').select('slug,name,name_pt,entity_type,category,area_slug,amount,spawn_probability,spawn_interval_seconds,medal_family,notes,source_url').eq('status','approved').order('entity_type').order('name');if(error){qs('#bestiaryGrid').innerHTML='<div class="bestiary-empty">Não foi possível carregar o Bestiário.</div>';return}entities=data||[];const areas=[...new Set(entities.map(x=>x.area_slug).filter(Boolean))].sort((a,b)=>(areaNames[a]||a).localeCompare(areaNames[b]||b));qs('#beastArea').innerHTML='<option value="">Todas as áreas</option>'+areas.map(a=>`<option value="${h(a)}">${h(areaNames[a]||a)}</option>`).join('');summary();render();renderBosses();}
function summary(){const c=t=>entities.filter(x=>x.entity_type===t).length;qs('#bestiarySummary').innerHTML=`<div><b>${entities.length}</b><span>Entidades</span></div><div><b>${c('monster')}</b><span>Monstros</span></div><div><b>${c('creature')}</b><span>Criaturas</span></div><div><b>${c('boss')}</b><span>Chefes</span></div>`}
function render(){if(!qs('#bestiaryGrid'))return;const s=(qs('#beastSearch')?.value||'').toLowerCase().trim(),t=qs('#beastType')?.value||'',a=qs('#beastArea')?.value||'';const list=entities.filter(x=>(!t||x.entity_type===t)&&(!a||x.area_slug===a)&&(!s||[x.name,x.name_pt,x.category,x.medal_family,x.notes,areaNames[x.area_slug]].join(' ').toLowerCase().includes(s)));qs('#bestiaryGrid').innerHTML=list.length?list.map(card).join(''):'<div class="bestiary-empty">Nenhum resultado para esse filtro.</div>'}
function card(x){return `<article class="beast-card"><span class="beast-icon">${icon[x.entity_type]||'❔'}</span><span class="tag ${x.entity_type==='boss'?'gold':x.entity_type==='creature'?'green':''}">${h(typeNames[x.entity_type]||x.entity_type)}</span><h3>${h(x.name)}</h3>${x.name_pt&&x.name_pt!==x.name?`<div class="pt">${h(x.name_pt)}</div>`:''}<div class="beast-meta"><span>${h(areaNames[x.area_slug]||x.area_slug||'MilMo')}</span>${x.category?`<span>${h(x.category)}</span>`:''}${x.medal_family?`<span>Medalha: ${h(x.medal_family)}</span>`:''}</div>${(x.amount||x.spawn_probability||x.spawn_interval_seconds)?`<div class="beast-spawn"><div><small>Qtd.</small><b>${x.amount??'—'}</b></div><div><small>Spawn</small><b>${h(x.spawn_probability||'—')}</b></div><div><small>Intervalo</small><b>${x.spawn_interval_seconds?x.spawn_interval_seconds+'s':'—'}</b></div></div>`:''}<p class="muted">${h(x.notes||'Registro verificado no Bestiário.')}</p>${x.source_url?`<a class="link" href="${h(x.source_url)}" target="_blank" rel="noopener">Fonte ↗</a>`:''}</article>`}
function renderBosses(){const bosses=entities.filter(x=>x.entity_type==='boss');qs('#bossLive').innerHTML=bosses.map(x=>`<article><span>👑</span><b>${h(x.name_pt||x.name)}</b><small>${h(areaNames[x.area_slug]||x.area_slug||'MilMo')} • ${h(x.notes||'Chefe verificado.')}</small></article>`).join('')||'<p class="muted">Nenhum chefe catalogado.</p>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();