(()=>{
const U='https://ayfdkemjykhxqirlzbzw.supabase.co',K='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(U,K):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const advMeta={
'The Horizon':['🧭','Horizon'],
'Summer Tide Saga':['🌊','Summer Tide'],
'Mice & Maniax':['🐭','Mice & Maniax'],
'Air World':['☁️','Air World']
};
let C={areas:[],missions:[],entities:[],items:[],tokens:[],knowledge:[]},active='Todos';
const css=document.createElement('style');css.textContent=`
.mp-nav{border:1px solid rgba(66,201,255,.25);background:linear-gradient(145deg,#092239,#071722);box-shadow:0 18px 40px rgba(0,0,0,.2)}.mp-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.mp-tabs button{padding:8px 11px;border:1px solid var(--line);border-radius:999px;background:#061827;color:#cbdce7;font-size:10px;cursor:pointer}.mp-tabs button.on{background:rgba(66,201,255,.12);border-color:rgba(66,201,255,.45);color:#fff}.mp-toolbar{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:12px}.mp-toolbar input{padding:11px;border:1px solid var(--line);border-radius:10px;background:#051521;color:#fff}.mp-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:10px 0}.mp-summary div{padding:10px;border:1px solid var(--line);border-radius:10px;background:#061827}.mp-summary b{display:block;color:var(--gold);font-size:19px}.mp-summary small{font-size:8px;color:var(--muted)}.mp-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.mp-card{border:1px solid var(--line);border-radius:14px;padding:12px;background:#071b2a}.mp-card.rich{border-color:rgba(139,237,119,.28)}.mp-card.stub{opacity:.76}.mp-card h4{margin:6px 0 2px}.mp-card .adv{font-size:8px;color:var(--muted)}.mp-counts{display:grid;grid-template-columns:repeat(4,1fr);gap:4px;margin:8px 0}.mp-counts div{padding:5px;border:1px solid var(--line);border-radius:7px;background:#061827;text-align:center}.mp-counts b{display:block;font-size:9px}.mp-counts small{font-size:6px;color:var(--muted)}.mp-status{display:flex;gap:5px;flex-wrap:wrap;margin:7px 0}.mp-status span{padding:4px 6px;border-radius:999px;border:1px solid var(--line);font-size:7px}.mp-status .ok{color:var(--green);border-color:rgba(139,237,119,.25)}.mp-status .base{color:var(--gold);border-color:rgba(255,213,74,.25)}.mp-modal .modalbox{width:min(1080px,96vw)}.mp-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mp-sec{border:1px solid var(--line);border-radius:13px;padding:13px;background:#071b2a}.mp-row{padding:7px 0;border-bottom:1px solid var(--line);font-size:10px}.mp-row:last-child{border-bottom:0}.mp-row b{display:block}.mp-row small{display:block;color:var(--muted);margin-top:2px}.mp-token-grid{display:grid;grid-template-columns:repeat(8,1fr);gap:5px}.mp-token{padding:8px 3px;text-align:center;border:1px solid var(--line);border-radius:8px;background:#061827;font-size:9px}.mp-empty{padding:10px;border-left:3px solid var(--gold);background:rgba(255,213,74,.05);border-radius:0 9px 9px 0;color:var(--muted);font-size:10px}@media(max-width:1050px){.mp-grid{grid-template-columns:repeat(3,1fr)}.mp-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:760px){.mp-grid,.mp-cols{grid-template-columns:1fr}.mp-summary{grid-template-columns:1fr 1fr}.mp-toolbar{grid-template-columns:1fr}}
`;document.head.appendChild(css);
async function load(){if(!db)return;const [a,m,g,i,t,k]=await Promise.all([
 db.from('milmo_areas').select('slug,name,adventure,era,description,source_url').order('adventure').order('name'),
 db.from('missions').select('area_slug,title,npc,objective,reward,source_url'),
 db.from('game_entities').select('area_slug,name,name_pt,entity_type,amount,spawn_probability,spawn_interval_seconds,notes,source_url').eq('status','approved'),
 db.from('game_items').select('area_slug,name,name_pt,item_type,acquisition_type,location_hint,probability,spawn_interval_seconds,notes,source_url').eq('status','approved'),
 db.from('exploration_tokens').select('area_slug,token_no,hint,coordinates,source_url'),
 db.from('knowledge_entries').select('section,title,content,source_url').eq('status','approved')
]);C={areas:a.data||[],missions:m.data||[],entities:g.data||[],items:i.data||[],tokens:t.data||[],knowledge:k.data||[]};render()}
function counts(slug){return {m:C.missions.filter(x=>x.area_slug===slug).length,g:C.entities.filter(x=>x.area_slug===slug).length,i:C.items.filter(x=>x.area_slug===slug).length,t:C.tokens.filter(x=>x.area_slug===slug).length}}
function render(){const q=($('#mpSearch')?.value||'').trim().toLowerCase();let rows=C.areas.filter(a=>(active==='Todos'||a.adventure===active)&&(!q||[a.name,a.adventure,a.description].join(' ').toLowerCase().includes(q)));const rich=rows.filter(a=>{const c=counts(a.slug);return c.m+c.g+c.i+c.t>0}).length;$('#mpSummary').innerHTML=`<div><b>${C.areas.length}</b><small>áreas cadastradas</small></div><div><b>4</b><small>aventuras oficiais</small></div><div><b>${C.missions.length}</b><small>missões no banco</small></div><div><b>${C.entities.length}</b><small>entidades aprovadas</small></div><div><b>${C.tokens.length}</b><small>tokens exatos</small></div>`;$('#mpGrid').innerHTML=rows.map(a=>card(a)).join('')||'<p class="muted">Nenhuma área encontrada.</p>';$('#mpResult').textContent=`${rows.length} áreas • ${rich} com conteúdo detalhado`;$$('[data-mp-area]').forEach(b=>b.onclick=()=>openArea(b.dataset.mpArea))}
function card(a){const c=counts(a.slug),total=c.m+c.g+c.i+c.t,rich=total>0,adv=advMeta[a.adventure]||['🗺️',a.adventure||'MilMo'];return `<article class="mp-card ${rich?'rich':'stub'}"><span style="font-size:26px">${adv[0]}</span><h4>${esc(a.name)}</h4><div class="adv">${esc(a.adventure||'Sem aventura')}</div><div class="mp-counts"><div><b>${c.m}</b><small>MISSÕES</small></div><div><b>${c.g}</b><small>ENTIDADES</small></div><div><b>${c.i}</b><small>ITENS</small></div><div><b>${c.t}</b><small>TOKENS</small></div></div><div class="mp-status"><span class="${rich?'ok':'base'}">${rich?'conteúdo detalhado':'base cadastrada'}</span>${c.t===8?'<span class="ok">rota 8/8</span>':''}</div><button class="btn secondary" data-mp-area="${a.slug}">Explorar área</button></article>`}
function openArea(slug){const a=C.areas.find(x=>x.slug===slug);if(!a)return;const m=C.missions.filter(x=>x.area_slug===slug),g=C.entities.filter(x=>x.area_slug===slug),i=C.items.filter(x=>x.area_slug===slug),t=C.tokens.filter(x=>x.area_slug===slug).sort((x,y)=>x.token_no-y.token_no),k=C.knowledge.filter(x=>x.section==='area:'+slug);$('#mpModal').classList.add('on');$('#mpTitle').textContent=a.name;$('#mpSub').textContent=(a.adventure||'MilMo')+' • '+(a.era||'Legacy');$('#mpBody').innerHTML=`<div class="mp-cols"><section class="mp-sec"><h3>📜 Missões (${m.length})</h3>${m.map(r=>`<div class="mp-row"><b>${esc(r.title)}</b>${r.npc?`<small>NPC: ${esc(r.npc)}</small>`:''}${r.objective?`<small>${esc(r.objective)}</small>`:''}${r.reward?`<small>Recompensa: ${esc(r.reward)}</small>`:''}</div>`).join('')||'<div class="mp-empty">Missões ainda em catalogação.</div>'}</section><section class="mp-sec"><h3>👾 Monstros, criaturas e NPCs (${g.length})</h3>${g.map(r=>`<div class="mp-row"><b>${esc(r.name_pt||r.name)}</b><small>${esc(r.entity_type)}${r.amount?' • qtd. '+r.amount:''}${r.spawn_probability?' • '+esc(r.spawn_probability):''}${r.spawn_interval_seconds?' • '+r.spawn_interval_seconds+' s':''}</small>${r.notes?`<small>${esc(r.notes)}</small>`:''}</div>`).join('')||'<div class="mp-empty">Entidades ainda em catalogação.</div>'}</section><section class="mp-sec"><h3>🎒 Itens (${i.length})</h3>${i.map(r=>`<div class="mp-row"><b>${esc(r.name_pt||r.name)}</b><small>${esc(r.location_hint||r.acquisition_type||r.item_type||'item')}${r.probability?' • '+esc(r.probability):''}${r.spawn_interval_seconds?' • '+r.spawn_interval_seconds+' s':''}</small></div>`).join('')||'<div class="mp-empty">Itens ainda em catalogação.</div>'}</section><section class="mp-sec"><h3>🧭 Tokens exatos (${t.length})</h3>${t.length?`<div class="mp-token-grid">${t.map(r=>`<div class="mp-token" title="${esc(r.hint||'')}"><b>${r.token_no}</b></div>`).join('')}</div>${t.map(r=>`<div class="mp-row"><b>Token ${r.token_no}</b><small>${esc(r.hint||'Posição registrada.')}</small></div>`).join('')}`:'<div class="mp-empty">A área pode ter checklist de exploração, mas a rota individual ainda não está validada no banco.</div>'}</section></div><section class="mp-sec" style="margin-top:12px"><h3>📚 Contexto e fontes</h3><p class="muted">${esc(a.description||'')}</p>${k.map(r=>`<div class="mp-row"><b>${esc(r.title)}</b><small>${esc(r.content)}</small>${r.source_url?`<a class="link" href="${esc(r.source_url)}" target="_blank" rel="noopener">fonte ↗</a>`:''}</div>`).join('')}${a.source_url?`<p style="margin-top:8px"><a class="link" href="${esc(a.source_url)}" target="_blank" rel="noopener">Fonte da área ↗</a></p>`:''}</section>`}
function add(){const p=$('#pedia');if(!p||$('#milmoPediaNavigator'))return;const s=document.createElement('section');s.id='milmoPediaNavigator';s.className='panel mp-nav';s.innerHTML=`<div class="section-head"><div><span class="eyebrow">NAVEGADOR UNIVERSAL</span><h2>MilMoPedia — aventura → área → conteúdo</h2><p>Uma única entrada para missões, monstros, criaturas, NPCs, itens, tokens e fontes.</p></div></div><div class="mp-tabs" id="mpTabs"><button class="on" data-mp-adv="Todos">🌐 Todos</button><button data-mp-adv="The Horizon">🧭 The Horizon</button><button data-mp-adv="Summer Tide Saga">🌊 Summer Tide Saga</button><button data-mp-adv="Mice & Maniax">🐭 Mice & Maniax</button><button data-mp-adv="Air World">☁️ Air World</button></div><div class="mp-toolbar"><input id="mpSearch" placeholder="Pesquisar área ou aventura..."><span id="mpResult" class="tag">carregando</span></div><div class="mp-summary" id="mpSummary"></div><div class="mp-grid" id="mpGrid"><p class="muted">Carregando catálogo...</p></div></section>`;p.insertBefore(s,p.firstElementChild);const modal=document.createElement('div');modal.id='mpModal';modal.className='modal mp-modal';modal.innerHTML=`<div class="modalbox"><div class="section-head"><div><span class="eyebrow">MILMOPEDIA • ÁREA</span><h2 id="mpTitle"></h2><p id="mpSub" class="muted"></p></div><button class="btn ghost" id="mpClose">Fechar</button></div><div id="mpBody"></div></div>`;document.body.appendChild(modal);$('#mpClose').onclick=()=>modal.classList.remove('on');modal.onclick=ev=>{if(ev.target===modal)modal.classList.remove('on')};$('#mpSearch').addEventListener('input',render);$$('[data-mp-adv]').forEach(b=>b.onclick=()=>{active=b.dataset.mpAdv;$$('[data-mp-adv]').forEach(x=>x.classList.toggle('on',x===b));render()});load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();