(()=>{
const U='https://ayfdkemjykhxqirlzbzw.supabase.co',K='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(U,K):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],e=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const A={
'air-village':{n:'A Vila',en:'The Village',ico:'🏘️',medal:'Villager',note:'Vila das War Birds abandonada. Aurax Repairs aparece na progressão.'},
'air-teichos':{n:'Teichos',en:'Teichos',ico:'🧱',medal:'Wall Guard',note:'Muralha antiga com 7 missões, Air Totem, Repair Manu e Volu.'},
'air-pyrgos':{n:'Pyrgos',en:'Pyrgos',ico:'🗼',medal:'Tower Climber',note:'Torre de nível 12 com elevadores ativados por três chaves.'},
'air-ainigma':{n:'Ainigma',en:'Ainigma',ico:'🧩',medal:'Puzzle Master',note:'Área de quebra-cabeça com The Ainigma e peças especiais.'},
'air-ejekatl':{n:'Ejekatl',en:'Ejekatl',ico:'🦅',medal:'Windy Warrior',note:'Área final dominada por War Birds e três chaves coloridas.'}
};
const css=document.createElement('style');css.textContent=`
.air-final-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.air-final-card{border:1px solid var(--line);border-radius:15px;padding:14px;background:linear-gradient(145deg,#0b2940,#071926)}.air-final-card .ico{font-size:32px}.air-final-card h3{margin:7px 0 2px;font-size:15px}.air-final-card p{font-size:10px;color:var(--muted);min-height:42px}.air-final-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:9px 0}.air-final-stats div{padding:7px;border:1px solid var(--line);border-radius:8px;background:#061827}.air-final-stats small{display:block;color:var(--muted);font-size:7px}.air-final-stats b{font-size:10px;color:var(--gold)}.air-route{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.air-route span{padding:7px 9px;border:1px solid var(--line);border-radius:999px;background:#061827;font-size:9px}.air-route i{color:var(--gold)}.air-final-modal .modalbox{width:min(980px,96vw)}.air-final-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}.air-final-sec{border:1px solid var(--line);border-radius:13px;padding:13px;background:#071b2a}.air-final-row{padding:7px 0;border-bottom:1px solid var(--line);font-size:10px}.air-final-row:last-child{border-bottom:0}.air-final-row b{display:block}.air-final-row small{color:var(--muted)}.air-audit{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.air-audit div{padding:10px;border:1px solid var(--line);border-radius:10px;background:#061827}.air-audit b{display:block;font-size:20px;color:var(--gold)}.air-audit span{font-size:8px;color:var(--muted)}@media(max-width:1100px){.air-final-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.air-final-grid,.air-final-cols{grid-template-columns:1fr}.air-audit{grid-template-columns:1fr 1fr}}`;
document.head.appendChild(css);
let cache={};
async function load(){if(!db)return;const slugs=Object.keys(A);const [m,i,g]=await Promise.all([db.from('missions').select('area_slug,title,npc,objective,reward,source_url').in('area_slug',slugs).order('title'),db.from('game_items').select('area_slug,name,name_pt,location_hint,probability,spawn_interval_seconds,source_url').in('area_slug',slugs).eq('status','approved').order('name'),db.from('game_entities').select('area_slug,name,name_pt,entity_type,amount,spawn_probability,spawn_interval_seconds,source_url').in('area_slug',slugs).eq('status','approved').order('name')]);cache={m:m.data||[],i:i.data||[],g:g.data||[]};render();audit()}
function render(){const host=$('#airFinalGrid');if(!host)return;host.innerHTML=Object.entries(A).map(([slug,a])=>{const mm=cache.m.filter(x=>x.area_slug===slug).length,ii=cache.i.filter(x=>x.area_slug===slug).length,gg=cache.g.filter(x=>x.area_slug===slug).length;return `<article class="air-final-card"><span class="ico">${a.ico}</span><h3>${e(a.n)}</h3><small class="muted">${e(a.en)}</small><p>${e(a.note)}</p><div class="air-final-stats"><div><small>Missões</small><b>${mm}</b></div><div><small>Itens</small><b>${ii}</b></div><div><small>Entidades</small><b>${gg}</b></div></div><button class="btn secondary" data-air-final="${slug}">Abrir</button></article>`}).join('');$$('[data-air-final]').forEach(b=>b.onclick=()=>open(b.dataset.airFinal))}
function open(slug){const a=A[slug];if(!a)return;const mm=cache.m.filter(x=>x.area_slug===slug),ii=cache.i.filter(x=>x.area_slug===slug),gg=cache.g.filter(x=>x.area_slug===slug);$('#airFinalModal').classList.add('on');$('#airFinalTitle').textContent=a.ico+' '+a.n;$('#airFinalSub').textContent=a.en+' • Medalha: '+a.medal;$('#airFinalBody').innerHTML=`<div class="air-final-cols"><section class="air-final-sec"><h3>📜 Missões (${mm.length})</h3>${mm.map(r=>`<div class="air-final-row"><b>${e(r.title)}</b>${r.npc?`<small>NPC: ${e(r.npc)}</small>`:''}${r.objective?`<small>${e(r.objective)}</small>`:''}${r.reward?`<small>Recompensa: ${e(r.reward)}</small>`:''}</div>`).join('')||'<p class="muted">Sem missões individualizadas além da progressão já conhecida.</p>'}</section><section class="air-final-sec"><h3>🎒 Itens (${ii.length})</h3>${ii.map(r=>`<div class="air-final-row"><b>${e(r.name_pt||r.name)}</b><small>${e(r.location_hint||'item')}${r.probability?' • '+e(r.probability):''}${r.spawn_interval_seconds?' • '+r.spawn_interval_seconds+' s':''}</small></div>`).join('')||'<p class="muted">Itens ainda em validação.</p>'}</section><section class="air-final-sec"><h3>👾 Entidades (${gg.length})</h3>${gg.map(r=>`<div class="air-final-row"><b>${e(r.name_pt||r.name)}</b><small>${e(r.entity_type)}${r.amount?' • qtd. '+r.amount:''}${r.spawn_probability?' • '+e(r.spawn_probability):''}${r.spawn_interval_seconds?' • '+r.spawn_interval_seconds+' s':''}</small></div>`).join('')||'<p class="muted">Entidades ainda em validação.</p>'}</section><section class="air-final-sec"><h3>🏅 Exploração</h3><p class="muted">Medalha: <b>${e(a.medal)}</b>. O checklist da área continua em 8 tokens; posições exatas só entram quando houver rota documentada.</p></section></div>`}
function audit(){const p=$('#airAudit');if(!p)return;const missionCount=cache.m.length,itemCount=cache.i.length,entityCount=cache.g.length,covered=Object.keys(A).filter(s=>cache.m.some(x=>x.area_slug===s)||cache.i.some(x=>x.area_slug===s)||cache.g.some(x=>x.area_slug===s)).length;p.innerHTML=`<div><b>${covered}/5</b><span>áreas com dados</span></div><div><b>${missionCount}</b><span>missões na reta final</span></div><div><b>${itemCount}</b><span>itens catalogados</span></div><div><b>${entityCount}</b><span>entidades catalogadas</span></div>`}
function add(){const p=$('#pedia');if(!p||$('#airFinalPanel'))return;const s=document.createElement('section');s.id='airFinalPanel';s.className='panel';s.innerHTML=`<div class="section-head"><div><span class="eyebrow">MUNDO AÉREO • RETA FINAL</span><h2>A Vila → Teichos → Pyrgos → Ainigma → Ejekatl</h2><p>Último bloco do Air World organizado com missões, itens, inimigos e progresso.</p></div><div class="agent-chip" id="airFinalAgent"><span class="ico">☁️</span><div><strong>Air World Guide</strong><small>Guia do Mundo Aéreo</small></div></div></div><div class="air-route"><span>🏘️ A Vila</span><i>→</i><span>🧱 Teichos</span><i>→</i><span>🗼 Pyrgos</span><i>→</i><span>🧩 Ainigma</span><i>→</i><span>🦅 Ejekatl</span></div><div class="air-audit" id="airAudit"></div><div class="air-final-grid" id="airFinalGrid" style="margin-top:12px"><p class="muted">Carregando...</p></div></section>`;const anchor=$('#miceDeepPanel')||$('#focusAreasPanel')||$('#questArchivePanel')||p.lastElementChild;p.insertBefore(s,anchor);const m=document.createElement('div');m.id='airFinalModal';m.className='modal air-final-modal';m.innerHTML=`<div class="modalbox"><div class="section-head"><div><span class="eyebrow">AIR WORLD • GUIA DE ÁREA</span><h2 id="airFinalTitle"></h2><p id="airFinalSub" class="muted"></p></div><button class="btn ghost" id="airFinalClose">Fechar</button></div><div id="airFinalBody"></div></div>`;document.body.appendChild(m);$('#airFinalClose').onclick=()=>m.classList.remove('on');m.onclick=ev=>{if(ev.target===m)m.classList.remove('on')};$('#airFinalAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent('Air World Guide')}catch{}};load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();