(()=>{
const U='https://ayfdkemjykhxqirlzbzw.supabase.co',K='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const db=window.supabase?.createClient?window.supabase.createClient(U,K):null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],e=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const order=['air-labyrinth','air-propylon','air-atrium','air-mezzanine','air-mechalon','air-palaestra','air-necropolis','air-temenos','air-aviary','air-ziggurat','air-village','air-teichos','air-pyrgos','air-ainigma','air-ejekatl'];
const meta={
'air-labyrinth':['Labirinto','The Amazing','🌫️'],'air-propylon':['Propylon','Head in the Clouds','☁️'],'air-atrium':['Atrium','Tower Topper','🏛️'],'air-mezzanine':['Mezzanine','Close to the Sun','⬆️'],'air-mechalon':['Mechalon','The Singed','🤖'],'air-palaestra':['Palaestra','Gladiator','🏟️'],'air-necropolis':['Necropolis','The Undead','💀'],'air-temenos':['Temenos','The Tranquil','🌿'],'air-aviary':['Aviário','Wingless Wonder','🪽'],'air-ziggurat':['Ziggurat','Archaeologist','🛕'],'air-village':['A Vila','Villager','🏘️'],'air-teichos':['Teichos','Wall Guard','🧱'],'air-pyrgos':['Pyrgos','Tower Climber','🗼'],'air-ainigma':['Ainigma','The Enigmatic','🧩'],'air-ejekatl':['Ejekatl','Windy Warrior','🦅']};
const css=document.createElement('style');css.textContent=`
.air-master-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:12px 0}.air-master-summary div{padding:12px;border:1px solid var(--line);border-radius:12px;background:#071b2a}.air-master-summary b{display:block;font-size:23px;color:var(--gold)}.air-master-summary span{font-size:8px;color:var(--muted)}.air-master-bar{height:11px;background:#051521;border-radius:999px;overflow:hidden}.air-master-bar i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--green),var(--gold));width:0}.air-master-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.air-master-card{border:1px solid var(--line);border-radius:13px;padding:12px;background:#071b2a}.air-master-head{display:flex;align-items:center;justify-content:space-between;gap:8px}.air-master-head b{font-size:12px}.air-master-medal{font-size:8px;color:var(--gold);margin:4px 0 8px}.air-master-mini{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}.air-master-mini div{padding:6px;border:1px solid var(--line);border-radius:7px;background:#061827}.air-master-mini small{display:block;font-size:7px;color:var(--muted)}.air-master-mini strong{font-size:9px}.air-tokenbar{height:6px;background:#051521;border-radius:999px;overflow:hidden;margin:8px 0}.air-tokenbar i{display:block;height:100%;background:var(--green);width:0}.air-master-card.complete{border-color:rgba(139,237,119,.4)}.air-master-card.partial{border-color:rgba(255,213,74,.32)}.air-doc{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.air-doc span{font-size:8px;padding:4px 6px;border:1px solid var(--line);border-radius:999px;color:#bcd0dc}.air-master-modal .modalbox{width:min(980px,96vw)}.air-master-cols{display:grid;grid-template-columns:1fr 1fr;gap:12px}.air-master-sec{border:1px solid var(--line);border-radius:13px;padding:13px;background:#071b2a}.air-master-row{padding:7px 0;border-bottom:1px solid var(--line);font-size:10px}.air-master-row:last-child{border-bottom:0}.air-master-row b{display:block}.air-master-row small{display:block;color:var(--muted);margin-top:2px}@media(max-width:1000px){.air-master-grid{grid-template-columns:repeat(2,1fr)}.air-master-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.air-master-grid,.air-master-cols{grid-template-columns:1fr}.air-master-summary{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(css);
let cache={areas:[],missions:[],items:[],entities:[],tokens:[],medals:[]};
function local(slug){try{return JSON.parse(localStorage.getItem('tokens_'+slug)||'[]')}catch{return[]}}
async function load(){if(!db)return;const [areas,m,i,g,t,a]=await Promise.all([
 db.from('milmo_areas').select('slug,name,description').eq('adventure','Air World'),
 db.from('missions').select('area_slug,title,npc,objective,reward,source_url').like('area_slug','air-%'),
 db.from('game_items').select('area_slug,name,name_pt,location_hint,probability,spawn_interval_seconds').like('area_slug','air-%').eq('status','approved'),
 db.from('game_entities').select('area_slug,name,name_pt,entity_type,amount,spawn_probability,spawn_interval_seconds').like('area_slug','air-%').eq('status','approved'),
 db.from('exploration_tokens').select('area_slug,token_no,hint,source_url').like('area_slug','air-%'),
 db.from('achievement_catalog').select('slug,title,description').like('slug','air-%').eq('category','Exploração')
]);cache={areas:areas.data||[],missions:m.data||[],items:i.data||[],entities:g.data||[],tokens:t.data||[],medals:a.data||[]};render();}
function render(){const complete=order.filter(s=>local(s).length===8).length,totalMarked=order.reduce((n,s)=>n+local(s).length,0),missionTotal=cache.missions.length,exactTokens=cache.tokens.length,officialMedals=cache.medals.length,missionPct=Math.min(100,missionTotal/95*100),playerPct=totalMarked/(order.length*8)*100;
$('#airMasterSummary').innerHTML=`<div><b>${complete}/15</b><span>Áreas concluídas</span></div><div><b>${totalMarked}/120</b><span>Tokens marcados por você</span></div><div><b>${missionTotal}/95</b><span>Missões verificadas no arquivo</span></div><div><b>${exactTokens}/120</b><span>Posições exatas de tokens</span></div><div><b>${officialMedals}/15</b><span>Medalhas oficiais catalogadas</span></div>`;$('#airPlayerBar').style.width=playerPct+'%';$('#airDocBar').style.width=missionPct+'%';$('#airMasterGrid').innerHTML=order.map(slug=>card(slug)).join('');$$('[data-air-master]').forEach(b=>b.onclick=()=>openArea(b.dataset.airMaster));const cont=order.find(s=>local(s).length>0&&local(s).length<8)||order.find(s=>local(s).length<8);$('#airContinue').textContent=cont?'Continuar: '+meta[cont][0]:'Mundo Aéreo 100%';$('#airContinue').onclick=()=>cont&&openArea(cont)}
function card(slug){const [name,medal,ico]=meta[slug],n=local(slug).length,mm=cache.missions.filter(x=>x.area_slug===slug).length,ii=cache.items.filter(x=>x.area_slug===slug).length,gg=cache.entities.filter(x=>x.area_slug===slug).length,tt=cache.tokens.filter(x=>x.area_slug===slug).length,cls=n===8?'complete':n>0?'partial':'';return `<article class="air-master-card ${cls}"><div class="air-master-head"><b>${ico} ${e(name)}</b><span class="tag">${n}/8</span></div><div class="air-master-medal">🏅 ${e(medal)}</div><div class="air-tokenbar"><i style="width:${n/8*100}%"></i></div><div class="air-master-mini"><div><small>Missões</small><strong>${mm}</strong></div><div><small>Itens</small><strong>${ii}</strong></div><div><small>Entidades</small><strong>${gg}</strong></div><div><small>Tokens exatos</small><strong>${tt}/8</strong></div></div><div class="air-doc">${tt===8?'<span>✓ rota de tokens completa</span>':'<span>rota parcial/em validação</span>'}${n===8?'<span>✓ medalha local</span>':''}</div><button class="btn secondary" style="margin-top:8px" data-air-master="${slug}">Detalhes</button></article>`}
function openArea(slug){const [name,medal,ico]=meta[slug],m=cache.missions.filter(x=>x.area_slug===slug),i=cache.items.filter(x=>x.area_slug===slug),g=cache.entities.filter(x=>x.area_slug===slug),t=cache.tokens.filter(x=>x.area_slug===slug).sort((a,b)=>a.token_no-b.token_no);$('#airMasterModal').classList.add('on');$('#airMasterTitle').textContent=ico+' '+name;$('#airMasterSub').textContent='Medalha oficial: '+medal+' • checklist local '+local(slug).length+'/8';$('#airMasterBody').innerHTML=`<div class="air-master-cols"><section class="air-master-sec"><h3>🧭 Tokens exatos (${t.length}/8)</h3>${t.map(r=>`<div class="air-master-row"><b>Token ${r.token_no}</b><small>${e(r.hint||'Posição registrada.')}</small></div>`).join('')||'<p class="muted">Rota individual ainda não validada.</p>'}</section><section class="air-master-sec"><h3>📜 Missões (${m.length})</h3>${m.map(r=>`<div class="air-master-row"><b>${e(r.title)}</b>${r.npc?`<small>NPC: ${e(r.npc)}</small>`:''}${r.objective?`<small>${e(r.objective)}</small>`:''}${r.reward?`<small>Recompensa: ${e(r.reward)}</small>`:''}</div>`).join('')||'<p class="muted">Sem missões individualizadas no banco.</p>'}</section><section class="air-master-sec"><h3>🎒 Itens (${i.length})</h3>${i.map(r=>`<div class="air-master-row"><b>${e(r.name_pt||r.name)}</b><small>${e(r.location_hint||'item')}${r.probability?' • '+e(r.probability):''}${r.spawn_interval_seconds?' • '+r.spawn_interval_seconds+' s':''}</small></div>`).join('')||'<p class="muted">Sem itens catalogados.</p>'}</section><section class="air-master-sec"><h3>👾 Entidades (${g.length})</h3>${g.map(r=>`<div class="air-master-row"><b>${e(r.name_pt||r.name)}</b><small>${e(r.entity_type)}${r.amount?' • qtd. '+r.amount:''}${r.spawn_probability?' • '+e(r.spawn_probability):''}${r.spawn_interval_seconds?' • '+r.spawn_interval_seconds+' s':''}</small></div>`).join('')||'<p class="muted">Sem entidades catalogadas.</p>'}</section></div>`}
function add(){const p=$('#pedia');if(!p||$('#airMasterPanel'))return;const s=document.createElement('section');s.id='airMasterPanel';s.className='panel';s.innerHTML=`<div class="section-head"><div><span class="eyebrow">PAINEL MESTRE • AIR WORLD</span><h2>Progresso único do Mundo Aéreo</h2><p>As 15 áreas em uma só visão: seu checklist, medalhas oficiais e cobertura documental do Hub.</p></div><button class="btn" id="airContinue">Continuar</button></div><div class="air-master-summary" id="airMasterSummary"></div><small class="muted">Seu progresso de exploração</small><div class="air-master-bar"><i id="airPlayerBar"></i></div><small class="muted" style="display:block;margin-top:8px">Cobertura do arquivo de missões (referência histórica: 95)</small><div class="air-master-bar"><i id="airDocBar"></i></div><div class="air-master-grid" id="airMasterGrid"><p class="muted">Carregando...</p></div></section>`;const anchor=$('#airFinalPanel')||$('#verifiedAirTokensPanel')||$('#adventureHubPanel')||p.firstElementChild;p.insertBefore(s,anchor);const modal=document.createElement('div');modal.id='airMasterModal';modal.className='modal air-master-modal';modal.innerHTML=`<div class="modalbox"><div class="section-head"><div><span class="eyebrow">AIR WORLD • VISÃO CONSOLIDADA</span><h2 id="airMasterTitle"></h2><p id="airMasterSub" class="muted"></p></div><button class="btn ghost" id="airMasterClose">Fechar</button></div><div id="airMasterBody"></div></div>`;document.body.appendChild(modal);$('#airMasterClose').onclick=()=>modal.classList.remove('on');modal.onclick=ev=>{if(ev.target===modal)modal.classList.remove('on')};load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',add);else add();
})();