(()=>{
const IURL='https://ayfdkemjykhxqirlzbzw.supabase.co',IKEY='sb_publishable_jYLFHHgTCQkufeykOAFmmQ_cyroudoy';
const idb=window.supabase?.createClient?window.supabase.createClient(IURL,IKEY):null;
const iq=s=>document.querySelector(s),iqa=s=>[...document.querySelectorAll(s)],ie=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let items=[];
const areaLabel={'rhubarb-island':'Ilha Ruibarbo','swamp-island':'Ilha do Pântano','kraken-island':'Ilha do Kraken','visitor-island':'Ilha dos Visitantes','ancient-forest':'Floresta Antiga','hidden-tor':'The Hidden Tor'};
const acqLabel={digging:'Cavando',ground:'No chão',shore:'Praia',boss_drop:'Drop de chefe',monster_drop:'Drop de monstro',medal_reward:'Recompensa de medalha',quest_reward:'Recompensa de missão'};
const acqIcon={digging:'⛏️',ground:'🌱',shore:'🐚',boss_drop:'👑',monster_drop:'⚔️',medal_reward:'🏅',quest_reward:'🎁'};
const css=document.createElement('style');css.textContent=`
.item-tools{display:grid;grid-template-columns:1fr 190px 190px auto;gap:8px;margin-bottom:14px}.item-tools input,.item-tools select{width:100%;padding:10px 11px;border:1px solid var(--line);border-radius:10px;background:#061827;color:#fff}.item-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.item-card{border:1px solid var(--line);border-radius:15px;padding:15px;background:linear-gradient(145deg,#0a2438,#061824)}.item-card h3{margin:7px 0 2px}.item-card .iname{font-size:11px;color:var(--muted)}.item-card .iicon{font-size:28px}.item-meta{display:flex;gap:5px;flex-wrap:wrap;margin:9px 0}.item-meta span{padding:5px 7px;border:1px solid var(--line);border-radius:999px;font-size:9px;color:#c8d8e3}.item-find{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:9px 0}.item-find div{padding:8px;border:1px solid var(--line);border-radius:9px;background:#051521}.item-find small{display:block;color:var(--muted);font-size:8px}.item-find b{font-size:10px;color:var(--gold)}.loot-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:12px 0}.loot-summary div{padding:11px;border:1px solid var(--line);border-radius:11px;background:#071b2a}.loot-summary b{display:block;font-size:21px;color:var(--gold)}.loot-summary span{font-size:9px;color:var(--muted)}.boss-loot-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.boss-loot{border:1px solid rgba(255,213,74,.26);border-radius:14px;padding:15px;background:rgba(255,213,74,.045)}.boss-loot .reward{font-size:23px}.boss-loot b{display:block;color:var(--gold);margin:5px 0}.rare-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.rare-item{padding:13px;border:1px solid rgba(176,131,255,.25);border-radius:13px;background:rgba(176,131,255,.055)}.rare-item b{display:block;color:#d7c0ff;margin-bottom:4px}.item-empty{grid-column:1/-1;padding:25px;text-align:center;color:var(--muted)}
@media(max-width:1000px){.item-grid{grid-template-columns:repeat(2,1fr)}.item-tools{grid-template-columns:1fr 1fr}.loot-summary{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.item-grid,.boss-loot-grid,.rare-strip{grid-template-columns:1fr}.item-tools{grid-template-columns:1fr}.loot-summary{grid-template-columns:1fr 1fr}}`;
document.head.appendChild(css);
function inject(){const p=iq('#pedia');if(!p||iq('#itemsPanel'))return;try{if(typeof agentInfo!=='undefined')agentInfo['Item Hunter']=['Caçador de Itens','🎒']}catch{}
const panel=document.createElement('section');panel.id='itemsPanel';panel.className='panel';panel.innerHTML=`<div class="section-head"><div><span class="eyebrow">ITENS, DROPS E RECOMPENSAS</span><h2>Onde encontrar cada item</h2><p>Catálogo com escavação, itens no chão, drops de monstros, drops de chefes e recompensas verificadas.</p></div><div class="agent-chip" id="itemAgent"><span class="ico">🎒</span><div><strong>Item Hunter</strong><small>Caçador de Itens</small></div></div></div><div class="loot-summary" id="lootSummary"><div><b>—</b><span>Itens</span></div><div><b>—</b><span>Cavando</span></div><div><b>—</b><span>Drops</span></div><div><b>—</b><span>Recompensas</span></div><div><b>—</b><span>Áreas</span></div></div><div class="item-tools"><input id="itemSearch" placeholder="Pesquisar: Mace Head, Cell, Fossil..."><select id="itemArea"><option value="">Todas as áreas</option></select><select id="itemAcq"><option value="">Todas as formas</option><option value="digging">Cavando</option><option value="ground">No chão</option><option value="boss_drop">Drop de chefe</option><option value="monster_drop">Drop de monstro</option><option value="medal_reward">Recompensa de medalha</option></select><button class="btn secondary" id="itemClear">Limpar</button></div><div class="item-grid" id="itemGrid"><div class="item-empty">Carregando itens...</div></div></section>`;
const anchor=iq('#bestiaryPanel')||iq('#legacyGuidePanel')||iq('#deepGuidePanel')||iq('#missionHubPanel')||p.lastElementChild;p.insertBefore(panel,anchor);
const boss=document.createElement('section');boss.id='bossLootPanel';boss.className='panel';boss.innerHTML=`<div class="section-head"><div><span class="eyebrow">LOOT VERIFICADO</span><h2>Recompensas especiais</h2><p>Somente drops e recompensas cuja ligação foi encontrada em fonte específica.</p></div></div><div class="boss-loot-grid" id="bossLootGrid"><p class="muted">Carregando...</p></div>`;p.insertBefore(boss,anchor);
const rare=document.createElement('section');rare.id='rareFindsPanel';rare.className='panel';rare.innerHTML=`<div class="section-head"><div><span class="eyebrow">ACHADOS RAROS</span><h2>Itens que vale a pena marcar</h2><p>Itens com chance baixa ou intervalo longo de reaparecimento.</p></div></div><div class="rare-strip" id="rareFinds"><p class="muted">Carregando...</p></div>`;p.insertBefore(rare,anchor);
iq('#itemAgent').onclick=()=>{try{if(typeof openAgent==='function')openAgent('Item Hunter')}catch{}};iq('#itemSearch').addEventListener('input',render);iq('#itemArea').addEventListener('change',render);iq('#itemAcq').addEventListener('change',render);iq('#itemClear').onclick=()=>{iq('#itemSearch').value='';iq('#itemArea').value='';iq('#itemAcq').value='';render()};load();}
async function load(){if(!idb){iq('#itemGrid').innerHTML='<div class="item-empty">Supabase indisponível.</div>';return}const {data,error}=await idb.from('game_items').select('slug,name,name_pt,item_type,area_slug,acquisition_type,related_entity_slug,location_hint,probability,spawn_interval_seconds,notes,source_url').eq('status','approved').order('area_slug',{ascending:true}).order('name');if(error){iq('#itemGrid').innerHTML='<div class="item-empty">Não foi possível carregar os itens.</div>';return}items=data||[];const areas=[...new Set(items.map(x=>x.area_slug).filter(Boolean))].sort((a,b)=>(areaLabel[a]||a).localeCompare(areaLabel[b]||b));iq('#itemArea').innerHTML='<option value="">Todas as áreas</option>'+areas.map(a=>`<option value="${ie(a)}">${ie(areaLabel[a]||a)}</option>`).join('');summary();render();renderSpecial();renderRare();}
function summary(){const digs=items.filter(x=>x.acquisition_type==='digging').length,drops=items.filter(x=>['boss_drop','monster_drop'].includes(x.acquisition_type)).length,rewards=items.filter(x=>x.acquisition_type.includes('reward')).length,areas=new Set(items.map(x=>x.area_slug).filter(Boolean)).size;iq('#lootSummary').innerHTML=`<div><b>${items.length}</b><span>Itens</span></div><div><b>${digs}</b><span>Cavando</span></div><div><b>${drops}</b><span>Drops</span></div><div><b>${rewards}</b><span>Recompensas</span></div><div><b>${areas}</b><span>Áreas</span></div>`}
function render(){if(!iq('#itemGrid'))return;const s=(iq('#itemSearch')?.value||'').toLowerCase().trim(),a=iq('#itemArea')?.value||'',t=iq('#itemAcq')?.value||'';const list=items.filter(x=>(!a||x.area_slug===a)&&(!t||x.acquisition_type===t)&&(!s||[x.name,x.name_pt,x.item_type,x.location_hint,x.notes,areaLabel[x.area_slug],acqLabel[x.acquisition_type]].join(' ').toLowerCase().includes(s)));iq('#itemGrid').innerHTML=list.length?list.map(card).join(''):'<div class="item-empty">Nenhum item encontrado com esses filtros.</div>'}
function card(x){return `<article class="item-card"><span class="iicon">${acqIcon[x.acquisition_type]||'🎒'}</span><span class="tag ${x.acquisition_type.includes('drop')?'gold':''}">${ie(acqLabel[x.acquisition_type]||x.acquisition_type)}</span><h3>${ie(x.name_pt||x.name)}</h3>${x.name_pt&&x.name_pt!==x.name?`<div class="iname">${ie(x.name)}</div>`:''}<div class="item-meta">${x.area_slug?`<span>${ie(areaLabel[x.area_slug]||x.area_slug)}</span>`:''}<span>${ie(x.item_type||'item')}</span></div><div class="item-find"><div><small>Onde</small><b>${ie(x.location_hint||'—')}</b></div><div><small>Chance</small><b>${ie(x.probability||'—')}</b></div></div>${x.spawn_interval_seconds?`<p class="muted">Reaparece em aproximadamente <b>${formatTime(x.spawn_interval_seconds)}</b>.</p>`:''}${x.notes?`<p class="muted">${ie(x.notes)}</p>`:''}${x.source_url?`<a class="link" href="${ie(x.source_url)}" target="_blank" rel="noopener">Fonte ↗</a>`:''}</article>`}
function formatTime(n){if(n>=3600)return Math.round(n/3600)+' h';if(n>=60)return Math.round(n/60)+' min';return n+' s'}
function renderSpecial(){const list=items.filter(x=>x.acquisition_type==='boss_drop'||x.acquisition_type==='medal_reward');iq('#bossLootGrid').innerHTML=list.map(x=>`<article class="boss-loot"><span class="reward">${x.acquisition_type==='boss_drop'?'👑':'🏅'}</span><b>${ie(x.name_pt||x.name)}</b><small>${ie(x.location_hint||acqLabel[x.acquisition_type]||'Recompensa')} ${x.probability?`• ${ie(x.probability)}`:''}</small>${x.notes?`<p class="muted">${ie(x.notes)}</p>`:''}${x.source_url?`<a class="link" href="${ie(x.source_url)}" target="_blank" rel="noopener">Prova ↗</a>`:''}</article>`).join('')||'<p class="muted">Nenhuma recompensa especial catalogada.</p>'}
function renderRare(){const list=items.filter(x=>(x.probability&&x.probability.includes('<1'))||(x.probability&&/^([0-9]|1[0-9])%$/.test(x.probability))||(x.spawn_interval_seconds>=600)).slice(0,12);iq('#rareFinds').innerHTML=list.map(x=>`<article class="rare-item"><b>${ie(x.name_pt||x.name)}</b><small>${ie(areaLabel[x.area_slug]||x.area_slug||'MilMo')} • ${ie(x.probability||'spawn longo')}${x.spawn_interval_seconds>=600?' • '+formatTime(x.spawn_interval_seconds):''}</small></article>`).join('')||'<p class="muted">Nenhum achado raro catalogado.</p>'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();