(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const d=typeof db!=='undefined'?db:null;
const css=document.createElement('style');css.textContent=`
.sts-strip{margin:10px 0 13px;padding:12px;border:1px solid rgba(66,201,255,.2);border-radius:12px;background:rgba(6,24,39,.76)}.sts-head{display:flex;justify-content:space-between;gap:10px;align-items:center}.sts-head b{font-size:12px}.sts-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:9px}.sts-stats div{padding:8px;border:1px solid var(--line);border-radius:9px;background:#051521}.sts-stats strong{display:block;color:var(--gold);font-size:16px}.sts-stats small{color:var(--muted);font-size:7px}.sts-bar{height:7px;background:#04111b;border-radius:999px;overflow:hidden;margin-top:9px}.sts-bar i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--green));width:0}.sts-quick{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.sts-quick button{padding:6px 8px;border:1px solid var(--line);border-radius:999px;background:#071b2a;color:#d4e2eb;font-size:8px;cursor:pointer}.sts-quick button:hover{border-color:rgba(66,201,255,.45)}@media(max-width:700px){.sts-stats{grid-template-columns:1fr 1fr}.sts-head{align-items:flex-start;flex-direction:column}}
`;document.head.appendChild(css);
let data=null;
async function load(){if(!d)return;const {data:areas}=await d.from('milmo_areas').select('slug,name').eq('adventure','Summer Tide Saga').order('name');const slugs=(areas||[]).map(x=>x.slug);if(!slugs.length)return;const [m,i,g,t]=await Promise.all([d.from('missions').select('area_slug').in('area_slug',slugs),d.from('game_items').select('area_slug').in('area_slug',slugs).eq('status','approved'),d.from('game_entities').select('area_slug').in('area_slug',slugs).eq('status','approved'),d.from('exploration_tokens').select('area_slug').in('area_slug',slugs)]);const rows=areas||[],missions=m.data||[],items=i.data||[],entities=g.data||[],tokens=t.data||[];const has=s=>missions.some(x=>x.area_slug===s)||items.some(x=>x.area_slug===s)||entities.some(x=>x.area_slug===s)||tokens.some(x=>x.area_slug===s);data={rows,missions,items,entities,tokens,covered:rows.filter(x=>has(x.slug)).length};mount()}
function mount(){const nav=q('#milmoPediaNavigator');if(!nav||q('#stsCoverageStrip')||!data)return;const tabs=q('#mpTabs');if(!tabs)return;const box=document.createElement('div');box.id='stsCoverageStrip';box.className='sts-strip';box.innerHTML=`<div class="sts-head"><div><b>🌊 Summer Tide Saga — cobertura documental</b><small class="muted" style="display:block">Os dados abaixo vêm do mesmo banco usado pelo Navegador Universal.</small></div><span class="tag">${data.covered}/${data.rows.length} áreas com conteúdo</span></div><div class="sts-stats"><div><strong>${data.rows.length}</strong><small>ÁREAS</small></div><div><strong>${data.missions.length}</strong><small>MISSÕES</small></div><div><strong>${data.entities.length}</strong><small>ENTIDADES</small></div><div><strong>${data.items.length}</strong><small>ITENS</small></div><div><strong>${data.tokens.length}</strong><small>TOKENS EXATOS</small></div></div><div class="sts-bar"><i style="width:${Math.round(data.covered/data.rows.length*100)}%"></i></div><div class="sts-quick"><button data-sts-jump="Lightmill Island">Ilha do Farol</button><button data-sts-jump="Mushroom Forest">Floresta dos Cogumelos</button><button data-sts-jump="Cozyville">Vila Aconchegante</button><button data-sts-jump="Sage Oak Island">Ilha do Sábio Carvalho</button></div>`;tabs.after(box);qa('[data-sts-jump]').forEach(b=>b.onclick=()=>jump(b.dataset.stsJump))}
function jump(name){const tab=qa('[data-mp-adv]').find(x=>x.dataset.mpAdv==='Summer Tide Saga');if(tab)tab.click();const search=q('#mpSearch');if(search){search.value=name;search.dispatchEvent(new Event('input',{bubbles:true}));search.scrollIntoView({behavior:'smooth',block:'center'})}}
function boot(){let n=0;const timer=setInterval(()=>{if(q('#milmoPediaNavigator')){clearInterval(timer);load()}else if(++n>30)clearInterval(timer)},250)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();